##################################################
#              Current configuration             #     
#                 May 2025                       #
##################################################

                  
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js #or wherever you ended up putting card-mod.js
  
# Activate config editor
config:

http:
  ip_ban_enabled: false
  login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

###  Yaml file locations ######
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
alert: !include alerts.yaml
template: !include templates.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
mqtt: !include mqtt.yaml
intent_script: !include intent_script.yaml
device_tracker: !include device_tracker.yaml


# location for sunrise and sunset times
# latitude: !secret latitude
# longitude: !secret longitude
# unit_system: metric
# time_zone: "europe/london" 

### Packages locations ######
homeassistant:
  packages: !include_dir_named packages
  media_dirs: 
    media: /media
  customize: !include customise.yaml

        
# influx db
#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: homeassistant
#  password: homeassistant
#  max_retries: 3
#  default_measurement: state

# influx db size



# Battery Notes Config 
battery_notes:
  enable_autodiscovery: true
  show_all_devices: false
  enable_replaced: true
  default_battery_low_threshold: 15
  battery_increase_threshold: 25
  hide_battery: false
  round_battery: false

######## Command Line stuff ############# 

command_line:
  - sensor:
      name: 'Lines of Code'
      unique_id: lines_of_code
      command: "find /config -name '*.yaml' | xargs cat | wc -l"
      scan_interval: 20000

  - sensor:
      unique_id: "ahc_blueprint_version"
      command: "curl https://raw.githubusercontent.com/panhans/HomeAssistant/refs/heads/main/blueprints/automation/panhans/advanced_heating_control.yaml"
      name: "AHC Blueprint Version"
      value_template: "{{ value | regex_findall('\\*\\*Version\\*\\*:(.+\\d+.\\d+.\\d+)', '\\1') | first | trim }}"
      scan_interval: 3600 # every hour


########## Shell Commands #############

shell_command:
  pushupdates_to_github: /bin/bash pushupdates.sh
  log_nmap_devices: /bin/bash log_nmap_devices.sh
  update_nmap_json: python3 /config/python_scripts/nmap_to_json.py

########## powercalc ##########  
powercalc:

####  python script #####

python_script:
  path: python_scripts

###### Rest Commands ######

rest_command:
  tablet_reboot:
    url: "http://192.168.0.154:2323/?cmd=rebootDevice&password=W3ath3r39"


  


      
