############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   17/08/2023                         #
#   @automation     :   sensors                            #
#   @description    :   not in a package file              #
#                                                          #
#                                                          #
#   @version        :   1.0                                #
#   @modified       :                                      #
############################################################


- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: ipv6_address
      arg: eth0
    - type: processor_use
    - type: processor_temperature
    - type: last_boot

- platform: sql
  db_url: !secret mariadb_url
  queries:
  - name: 'DataBase size'
    query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
    column: 'value'
    unit_of_measurement: MB

### mean indoor temperature for heating ######
- platform: statistics
  name: "Indoor Temperature Mean Last 24 Hours"
  unique_id: indoor_temperature_mean_24h
  entity_id: sensor.average_indoor_temperature
  state_characteristic: mean
  sampling_size: 100
  max_age: 
    hours: 24

### En-Suite Bathroom Humidity Change Over 5 Minutes ###
  name: "En-Suite Bathroom Humidity Change Over 5 Minutes"
  unique_id: es_humidity_change_over_5m
  entity_id: sensor.en_suite_temperature_and_humidity_humidity
  state_characteristic: change
  max_age:
    minutes: 1
  sampling_size: 60
  precision: 1



