
group:



automation:
#########################################################################
# Living Room lights turn on if dark and no other lights already on.    #
#########################################################################
  - id: living_room_lights_needed
    alias: Living Room Lights Needed
    initial_state: true
    mode: restart
    trigger:
    - entity_id: binary_sensor.living_room_fp2_presence_sensor_1
      platform: state
      from: 'off'
      to: 'on'
    condition:
    - condition: numeric_state
      entity_id: sensor.living_room_fp2_light_sensor_light_level
      below: input_number.low_light_threshold
    - condition: time
      after: '07:00:00'
      before: '22:15:00'
    - condition: state
      entity_id: group.living_room_lights
      state: 'off'
    action:
    - service: script.lights_w_level  
      data:
        level: 255

script:
  lights_w_level:
    - sequence:
      - service: light.turn_on
        entity_id: 
        data:
          brightness: '{{ level | int }}'
          color_temp: 369
  mode: single
  alias: Lights with Level
  
