alias: Adaptive Lighting Active Toggle
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.adaptive_lighting_active
    id: AL Active
  - platform: homeassistant
    event: start
    id: HA start
  - platform: state
    entity_id:
      - input_boolean.adaptive_lighting_sleep_mode_active
    id: Sleep Mode Active
  - platform: state
    entity_id:
      - binary_sensor.quiet_time_boys
    id: Sleep Mode Toggle Winter
  - platform: state
    entity_id:
      - binary_sensor.overnight
    id: Sleep Mode Toggle Summer
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - AL Active
              - HA start
        sequence:
          - variables:
              al_active: "{{ states('input_boolean.adaptive_lighting_active') }}"
          - data: {}
            entity_id:
              - switch.adaptive_lighting_back_door_zone
              - switch.adaptive_lighting_bedside_lamps
              - switch.adaptive_lighting_corner_lamp
              - switch.adaptive_lighting_hallway_lamp
              - switch.adaptive_lighting_hallway_lighting
              - switch.adaptive_lighting_kitchen_lights
              - switch.adaptive_lighting_spare_room_ceiling_lights
              - switch.adaptive_lighting_spare_room_lamps
              - switch.adaptive_lighting_spare_room_lamp_right
              - switch.adaptive_lighting_upstairs_landing
              - switch.adaptive_lighting_utility_light
            action: switch.turn_{{al_active}}
      - conditions:
          - condition: trigger
            id:
              - HA start
              - Sleep Mode Active
        sequence:
          - variables:
              sleep_mode: >-
                {{ states('input_boolean.adaptive_lighting_sleep_mode_active')
                }}
          - entity_id:
              - switch.adaptive_lighting_sleep_mode_back_door_zone
              - switch.adaptive_lighting_sleep_mode_bedside_lamps
              - switch.adaptive_lighting_sleep_mode_corner_lamp
              - switch.adaptive_lighting_sleep_mode_hallway_lamp
              - switch.adaptive_lighting_sleep_mode_hallway_lighting
              - switch.adaptive_lighting_sleep_mode_kitchen_lights
              - switch.adaptive_lighting_sleep_mode_spare_room_ceiling_lights
              - switch.adaptive_lighting_sleep_mode_spare_room_lamps
              - switch.adaptive_lighting_sleep_mode_spare_room_lamp_right
              - switch.adaptive_lighting_sleep_mode_upstairs_landing
              - switch.adaptive_lighting_sleep_mode_utility_light
            action: switch.turn_{{ sleep_mode }}
      - conditions:
          - condition: trigger
            id:
              - Sleep Mode Toggle Winter
          - condition: state
            entity_id: input_boolean.bst
            state: "off"
        sequence:
          - target:
              entity_id: input_boolean.adaptive_lighting_sleep_mode_active
            data: {}
            action: input_boolean.toggle
      - conditions:
          - condition: trigger
            id:
              - Sleep Mode Toggle Summer
          - condition: state
            entity_id: input_boolean.bst
            state: "on"
        sequence:
          - target:
              entity_id: input_boolean.adaptive_lighting_sleep_mode_active
            data: {}
            action: input_boolean.toggle
mode: restart
