alias: "ESPHome: Update all ESPHome devices"
sequence:
  - repeat:
      for_each: >-
        {{ states.update | selectattr('state','eq','on') |
        map(attribute='entity_id') |
        select('in',integration_entities('esphome')) | list }} 
      sequence:
        - action: update.install
          data: {}
          target:
            entity_id: "{{ repeat.item }}"
        - wait_template: "{{ is_state(repeat.item, 'off') }}"
          continue_on_timeout: true
description: ""
