alias: Alert when OneDrive is close to storage limit
description: Send notification to phone when drive needs cleanup.
triggers:
  - trigger: state
    entity_id:
      - sensor.onedrive_drive_state
    from: normal
    to: nearing
  - trigger: state
    entity_id:
      - sensor.onedrive_drive_state
    from: nearing
    to: critical
actions:
  - action: script.text_notify_dave
    data:
      title: OneDrive is almost full!
      message: >
        OneDrive has used up {{ states('sensor.my_drive_used_storage') }} of {{
        states('sensor.my_drive_total_available') }}GB.  Only {{
        states('sensor.my_drive_remaining_storage') }}GB remaining.
mode: single
