alias: All Govee Lighting
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_fp2_light_sensor_light_level
    below: input_number.low_light_threshold
    id: Low Light
    for:
      seconds: 20
  - platform: numeric_state
    entity_id: sensor.living_room_fp2_light_sensor_light_level
    above: input_number.upper_light_threshold_level
    id: Good Light
    for:
      seconds: 20
  - platform: state
    entity_id:
      - binary_sensor.morning
    from: "off"
    to: "on"
    id: Morning
  - platform: state
    entity_id:
      - sun.sun
    from: below_horizon
    to: above_horizon
    id: sunrise
  - platform: state
    entity_id:
      - binary_sensor.afternoon
    from: "off"
    to: "on"
    id: Afternoon
  - platform: state
    entity_id:
      - binary_sensor.evening
    from: "off"
    to: "on"
    id: Evening
  - platform: state
    entity_id:
      - sun.sun
    from: above_horizon
    to: below_horizon
    id: sunset
  - platform: state
    entity_id:
      - binary_sensor.overnight
    from: "off"
    to: "on"
    id: Overnight
    for:
      hours: 1
      minutes: 0
      seconds: 0
  - platform: state
    entity_id:
      - switch.living_room_tv
    from: "off"
    to: "on"
    id: TV on
  - platform: state
    entity_id:
      - switch.living_room_tv
    from: "on"
    to: "off"
    id: TV off
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Low Light
          - condition: state
            entity_id: switch.living_room_tv
            state: "on"
        sequence:
          - data: {}
            target:
              entity_id: light.dreamview_g1_pro_2
            action: light.turn_on
      - conditions:
          - condition: trigger
            id: Good Light
          - condition: state
            entity_id: switch.living_room_tv
            state: "on"
        sequence:
          - data: {}
            target:
              entity_id: light.dreamview_g1_pro_2
            action: light.turn_off
      - conditions:
          - condition: trigger
            id:
              - Morning
        sequence:
          - target:
              entity_id: light.glide_lights_right_2
            data:
              brightness_pct: 1
              effect: Morning
            action: light.turn_on
          - target:
              entity_id: light.govee_glide_left_2
            data:
              brightness_pct: 1
              effect: Morning
            action: light.turn_on
          - target:
              entity_id: light.stair_lights_2
            data:
              brightness_pct: 5
              effect: Morning
            action: light.turn_on
          - target:
              entity_id: light.xmas_string_lights_3_2
            data:
              brightness_pct: 50
              effect: Morning
            action: light.turn_on
          - condition: state
            entity_id: input_boolean.wakeup_lights
            state: "off"
          - delay:
              hours: 0
              minutes: 23
              seconds: 0
              milliseconds: 0
          - condition: state
            entity_id: input_boolean.wakeup_lights
            state: "off"
          - target:
              entity_id: light.bed_lamps_3
            data:
              brightness_pct: 5
              effect: Morning
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - Afternoon
        sequence:
          - target:
              entity_id: light.glide_lights_right_2
            data:
              brightness_pct: 1
              effect: Rustling Leaves
            action: light.turn_on
          - target:
              entity_id: light.govee_glide_left_2
            data:
              brightness_pct: 1
              effect: Rustling Leaves
            action: light.turn_on
          - target:
              entity_id: light.stair_lights_2
            data:
              brightness_pct: 5
              effect: Afternoon
            action: light.turn_on
          - target:
              entity_id: light.bed_lamps_3
            data:
              brightness_pct: 5
              effect: Afternoon
            action: light.turn_on
          - target:
              entity_id: light.xmas_string_lights_3_2
            data:
              brightness_pct: 50
              effect: Afternoon
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - Evening
        sequence:
          - target:
              entity_id: light.glide_lights_right_2
            data:
              brightness_pct: 1
              effect: Candlelight
            action: light.turn_on
          - target:
              entity_id: light.govee_glide_left_2
            data:
              brightness_pct: 1
              effect: Candlelight
            action: light.turn_on
          - target:
              entity_id: light.stair_lights_2
            data:
              brightness_pct: 5
              effect: Dating
            action: light.turn_on
          - target:
              entity_id: light.bed_lamps_3
            data:
              brightness_pct: 5
              effect: Dating
            action: light.turn_on
          - target:
              entity_id: light.xmas_string_lights_3_2
            data:
              brightness_pct: 50
              effect: Gobi Desert
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - Overnight
        sequence:
          - target:
              entity_id:
                - light.glide_lights_right_2
                - light.govee_glide_left_2
                - light.xmas_string_lights_3_2
            data: {}
            action: light.turn_off
      - conditions:
          - condition: trigger
            id:
              - sunrise
          - condition: state
            entity_id: binary_sensor.morning
            state: "on"
        sequence:
          - if:
              - condition: state
                entity_id: input_boolean.wakeup_lights
                state: "off"
            then:
              - target:
                  entity_id: light.bed_lamps_3
                data:
                  brightness_pct: 5
                  effect: Sunrise
                action: light.turn_on
            alias: Turn on bed lamps if wakeup lights off
          - target:
              entity_id: light.stair_lights_2
            data:
              brightness_pct: 5
              effect: Sunrise
            action: light.turn_on
          - target:
              entity_id: light.govee_glide_left_2
            data:
              brightness_pct: 5
              effect: Sunrise
            action: light.turn_on
          - target:
              entity_id: light.glide_lights_right_2
            data:
              brightness_pct: 5
              effect: Sunrise
            action: light.turn_on
          - target:
              entity_id: light.xmas_string_lights_3_2
            data:
              brightness_pct: 50
              effect: Sunrise
            action: light.turn_on
          - delay:
              minutes: 30
          - target:
              entity_id: light.glide_lights_right_2
            data:
              brightness_pct: 1
              effect: Morning
            action: light.turn_on
          - target:
              entity_id: light.govee_glide_left_2
            data:
              brightness_pct: 1
              effect: Morning
            action: light.turn_on
          - target:
              entity_id: light.stair_lights_2
            data:
              brightness_pct: 5
              effect: Morning
            action: light.turn_on
          - target:
              entity_id: light.bed_lamps_3
            data:
              brightness_pct: 5
              effect: Morning
            action: light.turn_on
          - target:
              entity_id: light.xmas_string_lights_3_2
            data:
              brightness_pct: 50
              effect: Morning
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - TV on
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.day
                state: "off"
              - condition: numeric_state
                entity_id: sensor.living_room_fp2_light_sensor_light_level
                below: input_number.low_light_threshold
        sequence:
          - target:
              entity_id: light.dreamview_g1_pro_2
            data: {}
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - TV off
          - condition: state
            entity_id: light.dreamview_g1_pro_2
            state: "on"
        sequence:
          - target:
              entity_id: light.dreamview_g1_pro_2
            data: {}
            action: light.turn_off
      - conditions:
          - condition: trigger
            id:
              - sunset
        sequence:
          - if:
              - condition: state
                entity_id: binary_sensor.overnight
                state: "off"
            then:
              - target:
                  entity_id: light.bed_lamps_3
                data:
                  brightness_pct: 5
                  effect: Warm
                action: light.turn_on
          - target:
              entity_id: light.stair_lights_2
            data:
              brightness_pct: 5
              effect: Warm
            action: light.turn_on
          - target:
              entity_id: light.govee_glide_left_2
            data:
              brightness_pct: 5
              effect: Sunset Glow
            action: light.turn_on
          - target:
              entity_id: light.glide_lights_right_2
            data:
              brightness_pct: 5
              effect: Sunset Glow
            action: light.turn_on
          - target:
              entity_id: light.xmas_string_lights_3_2
            data:
              brightness_pct: 50
              effect: Warm
            action: light.turn_on
          - delay:
              minutes: 30
          - if:
              - condition: state
                entity_id: binary_sensor.afternoon
                state: "on"
            then:
              - target:
                  entity_id: light.glide_lights_right_2
                data:
                  brightness_pct: 1
                  effect: Rustling Leaves
                action: light.turn_on
              - target:
                  entity_id: light.govee_glide_left_2
                data:
                  brightness_pct: 1
                  effect: Rustling Leaves
                action: light.turn_on
              - target:
                  entity_id: light.stair_lights_2
                data:
                  brightness_pct: 5
                  effect: Afternoon
                action: light.turn_on
              - target:
                  entity_id: light.xmas_string_lights_3_2
                data:
                  brightness_pct: 50
                  effect: Afternoon
                action: light.turn_on
              - target:
                  entity_id: light.bed_lamps_3
                data:
                  brightness_pct: 5
                  effect: Afternoon
                action: light.turn_on
            else:
              - target:
                  entity_id: light.glide_lights_right_2
                data:
                  brightness_pct: 1
                  effect: Candlelight
                action: light.turn_on
              - target:
                  entity_id: light.govee_glide_left_2
                data:
                  brightness_pct: 1
                  effect: Candlelight
                action: light.turn_on
              - target:
                  entity_id: light.stair_lights_2
                data:
                  brightness_pct: 5
                  effect: Dating
                action: light.turn_on
              - target:
                  entity_id: light.xmas_string_lights_3_2
                data:
                  brightness_pct: 50
                  effect: Gobi Desert
                action: light.turn_on
              - if:
                  - condition: state
                    entity_id: binary_sensor.overnight
                    state: "off"
                then:
                  - target:
                      entity_id: light.bed_lamps_3
                    data:
                      brightness_pct: 5
                      effect: Dating
                    action: light.turn_on
mode: parallel
initial_state: true
