alias: Aurora Alert
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.aurora_visibility_aurora_visibility
    above: 10
    id: aurora on
    trigger: numeric_state
  - entity_id:
      - sensor.aurora_visibility_aurora_visibility
    below: 5
    id: aurora off
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: aurora on
        sequence:
          - action: script.text_notify_parents
            metadata: {}
            data:
              title: AURORA ALERT - HIGHLY PROBABLE
              message: There may be a visible aurora tonight
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: "on"
          - action: script.jarvis_speech_engine
            data:
              where: dave
              message: >-
                Sorry to interrupt, but there is a good chance of seeing the
                Northern Lights tonight.
      - conditions:
          - condition: trigger
            id: aurora off
        sequence:
          - action: script.text_notify_parents
            metadata: {}
            data:
              title: AURORA ALERT - ALERT OVER
              message: That will be that for the Northern Lights then.
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: "on"
          - action: script.jarvis_speech_engine
            data:
              where: dave
              message: >-
                Sorry to interrupt, but there is a good chance you missed the
                Northern Lights tonight.
