alias: Back Door Light Needed
description: ""
mode: single
triggers:
  - entity_id:
      - switch.back_door_light_switch
    from: "off"
    to: "on"
    trigger: state
  - entity_id:
      - switch.back_door_light_switch
    from: "on"
    to: "off"
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.back_door_light
            state: "off"
        sequence:
          - data: {}
            target:
              entity_id: light.back_door_light
            action: light.turn_on
    default:
      - data: {}
        target:
          entity_id: light.back_door_light
        action: light.turn_off
      - action: script.back_door_light_dim_when_door_closed
        metadata: {}
        data: {}
