alias: Battery Replaced
description: Battery Replaced
mode: queued
triggers:
  - event_type: battery_notes_battery_increased
    trigger: event
conditions: []
actions:
  - action: battery_notes.set_battery_replaced
    data:
      device_id: "{{ trigger.event.data.device_id }}"
      source_entity_id: "{{ trigger.event.data.source_entity_id }}"

