alias: Birthday Announcements
description: ""
triggers:
  - event: start
    offset: "7:45:0"
    entity_id: calendar.birthdays
    trigger: calendar
conditions:
  - condition: template
    value_template: "{{ is_state('input_boolean.audible_notifications','on') }}"
actions:
  - alias: Pump up the volume
    action: media_player.volume_set
    target:
      entity_id: media_player.living_room_pop
    data:
      volume_level: 0.4
  - action: script.birthday_announcement
    data:
      where: living_room
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - data:
      entity_id: media_player.living_room_pop
      media_content_id: Awesome Birthday Song in everywhere group
      media_content_type: AMAZON_MUSIC
    action: media_player.play_media
    alias: Play Happy Birthday everywhere.
  - action: media_player.volume_set
    target:
      entity_id: media_player.living_room_pop
    data:
      volume_level: 0.4
    alias: Let down the volume
mode: single
initial_state: true
