alias: Boys Bedtime Announcements v2.0
description: ""
triggers:
  - at: input_datetime.school_night_jamie
    id: School Bedtime Jamie
    trigger: time
    enabled: true
  - at: input_datetime.school_night_sean
    id: School Bedtime Sean
    trigger: time
    enabled: true
  - at: input_datetime.non_school_night
    id: Non School Bedtime
    trigger: time
    enabled: true
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - School Bedtime Sean
          - condition: state
            entity_id: sensor.school_tomorrow
            state: "True"
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: "on"
          - condition: state
            entity_id: input_boolean.seans_bedtime_announcement_played
            state: "off"
        sequence:
          - action: script.sean_bedtime_announcement
            data: {}
      - conditions:
          - condition: trigger
            id:
              - School Bedtime Jamie
          - condition: state
            entity_id: sensor.school_tomorrow
            state: "True"
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: "on"
          - condition: state
            entity_id: input_boolean.jamies_bedtime_announcement_played
            state: "off"
        sequence:
          - action: script.jamie_bedtime_announcement
            data: {}
      - conditions:
          - condition: trigger
            id: Non School Bedtime
          - condition: state
            entity_id: sensor.school_tomorrow
            state: "False"
          - condition: state
            entity_id: input_boolean.audible_notifications
            state: "on"
          - condition: and
            conditions:
              - condition: state
                entity_id: input_boolean.seans_bedtime_announcement_played
                state: "off"
              - condition: state
                entity_id: input_boolean.jamies_bedtime_announcement_played
                state: "off"
        sequence:
          - action: script.boys_bedtime_announcement
            data: {}
mode: single
initial_state: true
