alias: Boys Bedroom Presence and Lights
description: ""
triggers:
  - entity_id:
      - binary_sensor.jamie_room_presence_occupancy
    from: "off"
    to: "on"
    id: Jamie Presence
    trigger: state
  - entity_id:
      - binary_sensor.jamies_room_occupied
    from: "on"
    to: "off"
    id: Jamie Absence
    trigger: state
  - entity_id:
      - binary_sensor.sean_room_presence_occupancy
    from: "off"
    to: "on"
    id: Sean Presence
    trigger: state
  - entity_id:
      - binary_sensor.seans_room_occupied
    from: "on"
    to: "off"
    id: Sean Absence
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Jamie Presence
        sequence:
          - parallel:
              - action: input_text.set_value
                metadata: {}
                data:
                  value: jamies_room
                target:
                  entity_id: input_text.room_presence
              - action: input_boolean.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id: input_boolean.room_occupied_jamie_s_room
              - if:
                  - condition: numeric_state
                    entity_id: sensor.jamies_room_light_level
                    below: input_number.low_light_threshold
                  - condition: time
                    after: "08:00:00"
                    before: "19:45:00"
                    weekday:
                      - sun
                      - sat
                      - fri
                      - thu
                      - wed
                      - tue
                      - mon
                then:
                  - action: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.jamies_light_toggle
                    data: {}
                alias: If low light between 8am and 7:45pm turn on the light.
            alias: Set text and toggles.
      - conditions:
          - condition: trigger
            id:
              - Sean Presence
        sequence:
          - alias: Set text and toggles.
            parallel:
              - action: input_text.set_value
                metadata: {}
                data:
                  value: seans_room
                target:
                  entity_id: input_text.room_presence
              - action: input_boolean.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id: input_boolean.room_occupied_sean_s_room
              - alias: If low light between 8am and 7:45pm turn on the light.
                if:
                  - condition: numeric_state
                    entity_id: sensor.seans_room_light_level
                    below: input_number.low_light_threshold
                  - condition: time
                    after: "08:00:00"
                    before: "19:45:00"
                    weekday:
                      - sun
                      - sat
                      - fri
                      - thu
                      - wed
                      - tue
                      - mon
                then:
                  - action: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.seans_light_toggle
                    data: {}
      - conditions:
          - condition: trigger
            id:
              - Jamie Absence
        sequence:
          - action: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id:
                - input_boolean.room_occupied_jamie_s_room
                - input_boolean.jamies_light_toggle
      - conditions:
          - condition: trigger
            id:
              - Sean Absence
        sequence:
          - action: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id:
                - input_boolean.room_occupied_sean_s_room
                - input_boolean.seans_light_toggle
mode: single
