alias: "Charge Battery from Clipped Solar "
description: Charges battery from clipped DC power when solar production estimate is high.
mode: single
triggers:
  - entity_id:
      - input_boolean.home_battery_grid_charging
      - >-
        binary_sensor.octopus_energy_target_intermittent_best_rates_3_hours_overnight
    to: "off"
    from: "on"
    id: Grid Charge Finished
    alias: When battery finishes grid charge.
    trigger: state
  - entity_id:
      - sensor.solaredge_b1_state_of_energy
    above: 99.5
    id: Charge Complete
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Grid Charge Finished
          - condition: template
            value_template: >-
              {{
              is_state_attr('binary_sensor.octopus_energy_target_intermittent_best_rates_3_hours_overnight','next_duration_in_hours',0)}}
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_forecast_today
            above: 40
        sequence:
          - action: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.charge_rate_limited
          - action: number.set_value
            target:
              entity_id:
                - number.solaredge_i1_storage_charge_limit
            data:
              value: "{{states('input_number.storage_charge_limit')|float(0)}}"
      - conditions:
          - condition: trigger
            id:
              - Charge Complete
          - condition: state
            entity_id: input_boolean.charge_rate_limited
            state: "on"
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.charge_rate_limited
            data: {}
          - action: number.set_value
            metadata: {}
            data:
              value: "7000"
            target:
              entity_id: number.solaredge_i1_storage_charge_limit
