alias: "Charge Battery from Clipped Solar "
description: >-
  Effectively charges battery from clipped DC power when solar production
  estimate is high. In reality, the charge rate is dynamically adjusted to allow
  max DC production while the battery charges.
triggers:
  - alias: When battery finishes grid charge or car finishes charging.
    entity_id:
      - input_boolean.home_battery_grid_charging
      - input_boolean.rolec_battery_master
    to: "off"
    from: "on"
    id: Grid Charge Finished
    trigger: state
  - trigger: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: 10
    id: Smart Sunrise Trigger
  - entity_id:
      - sensor.solaredge_b1_state_of_energy
    above: 99.5
    id: Charge Complete
    trigger: numeric_state
  - trigger: time_pattern
    minutes: /5
    id: Update
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Grid Charge Finished
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_forecast_today
            above: 30
        sequence:
          - action: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.charge_rate_limited
          - action: number.set_value
            target:
              entity_id:
                - number.solaredge_i1_storage_charge_limit
            data:
              value: "{{states('input_number.storage_charge_limit')|float(0)}}"
      - conditions:
          - condition: trigger
            id: Smart Sunrise Trigger
          - condition: state
            entity_id: input_boolean.charge_rate_limited
            state: "off"
          - condition: state
            entity_id: input_boolean.home_battery_grid_charging
            state: "off"
          - condition: numeric_state
            entity_id: sensor.solcast_pv_forecast_forecast_today
            above: 30
        sequence:
          - target:
              entity_id: input_boolean.charge_rate_limited
            action: input_boolean.turn_on
            data: {}
          - target:
              entity_id: number.solaredge_i1_storage_charge_limit
            data:
              value: "{{ states('input_number.storage_charge_limit') | float(0) }}"
            action: number.set_value
      - conditions:
          - condition: trigger
            id:
              - Charge Complete
          - condition: state
            entity_id: input_boolean.charge_rate_limited
            state: "on"
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.charge_rate_limited
            data: {}
          - action: number.set_value
            metadata: {}
            data:
              value: "7000"
            target:
              entity_id: number.solaredge_i1_storage_charge_limit
      - conditions:
          - condition: trigger
            id:
              - Update
          - condition: state
            entity_id: input_boolean.charge_rate_limited
            state: "on"
        sequence:
          - action: number.set_value
            target:
              entity_id: number.solaredge_i1_storage_charge_limit
            data:
              value: "{{ states('sensor.battery_charge_limit_dynamic') | float(0) }}"
            alias: Set charge rate limit dynamically to a max 2160W
mode: parallel
max: 3
