############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   19/08/2023                         #
#   @automation     :   Cloakroom Lights with Presence     #
#   @description    :                                      #
#                                                          #
#                                                          #
#   @version        :   1.03                               #
#   @modified       :                                      #
############################################################

alias: Cloakroom Lights on with Presence
description: Lights on and off with presence and timer
mode: restart
triggers:
  - entity_id:
      - binary_sensor.cloakroom_presence_occupancy
    from: "off"
    to: "on"
    id: Presence
    alias: When someone goes into the cloakroom.
    trigger: state
  - entity_id:
      - binary_sensor.cloakroom_presence_occupancy
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: Absence
    alias: When someone leaves the cloakroom.
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.cloakroom_light
    id: Timer Done
    alias: When cloakroom timer runs down.
    enabled: true
    trigger: event
  - entity_id:
      - light.cloakroom_switch_left
    from: "off"
    to: "on"
    id: Switch on
    alias: When light is turned on manually.
    trigger: state
  - entity_id:
      - sensor.cloakroom_presence_illuminance_lux
    below: 20
    id: Low Light
    alias: When light level is low.
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Presence
          - condition: state
            entity_id: binary_sensor.quiet_time_boys
            state: "off"
        sequence:
          - alias: Turn on extractor.
            action: switch.turn_on
            target:
              entity_id:
                - switch.cloakroom_switch_right
            data: {}
          - data: {}
            target:
              entity_id: timer.cloakroom_light
            action: timer.start
          - condition: or
            conditions:
              - condition: sun
                before: sunrise
                after: sunset
              - condition: numeric_state
                entity_id: sensor.cloakroom_presence_illuminance_lux
                below: 20
          - alias: Turn on light.
            action: switch.turn_on
            target:
              entity_id:
                - switch.cloakroom_switch_left
            data: {}
        alias: When someone enters cloakroom outside of quite time.
      - conditions:
          - condition: trigger
            id:
              - Presence
          - condition: state
            entity_id: binary_sensor.quiet_time_boys
            state: "on"
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: sensor.cloakroom_presence_illuminance_lux
                below: 20
              - condition: sun
                before: sunrise
                after: sunset
        sequence:
          - action: switch.turn_on
            target:
              entity_id:
                - switch.cloakroom_switch_left
            data: {}
            alias: Turn on light only.
          - data: {}
            target:
              entity_id: timer.cloakroom_light
            action: timer.start
        alias: When someone enters cloakroom during quite time.
      - conditions:
          - condition: trigger
            id:
              - Absence
          - condition: state
            entity_id: timer.cloakroom_light
            state: idle
        sequence:
          - data: {}
            target:
              entity_id:
                - switch.cloakroom_switch_left
            action: switch.turn_off
            alias: Turn off the light.
          - condition: state
            entity_id: switch.cloakroom_switch_right
            state: "on"
            alias: Check if the extractor is on.
          - data: {}
            target:
              entity_id:
                - switch.cloakroom_switch_right
            action: switch.turn_off
            alias: Turn off the extractor.
        alias: When someone leaves the cloakroom.
      - conditions:
          - condition: trigger
            id:
              - Switch on
          - condition: state
            entity_id: binary_sensor.quiet_time_boys
            state: "off"
        sequence:
          - data: {}
            target:
              entity_id: timer.cloakroom_light
            action: timer.start
          - target:
              entity_id: switch.cloakroom_switch_right
            data: {}
            action: switch.turn_on
            alias: Turn on extractor.
        alias: Light switch manually turned on.
      - conditions:
          - condition: trigger
            id:
              - Timer Done
          - condition: state
            entity_id: binary_sensor.cloakroom_presence_occupancy
            state: "off"
        sequence:
          - if:
              - condition: state
                entity_id: binary_sensor.quiet_time_boys
                state: "off"
            then:
              - action: switch.turn_off
                target:
                  entity_id: switch.cloakroom_switch_right
                data: {}
              - if:
                  - condition: state
                    entity_id: switch.cloakroom_switch_left
                    state: "on"
                then:
                  - action: switch.turn_off
                    target:
                      entity_id: switch.cloakroom_switch_left
                    data: {}
            else:
              - action: switch.turn_off
                target:
                  entity_id: switch.cloakroom_switch_left
                data: {}
        alias: When cloakroom timer runs down.
      - conditions:
          - condition: trigger
            id:
              - Low Light
          - condition: state
            entity_id: binary_sensor.cloakroom_occupied
            state: "on"
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.cloakroom_switch_left
            data: {}
            alias: Turn on the light.


