alias: Cloakroom Lights on with Presence
description: Lights on and off with presence and timer
triggers:
  - entity_id:
      - binary_sensor.cloakroom_presence_occupancy
    from: "off"
    to: "on"
    id: Presence
    alias: When someone goes into the cloakroom.
    trigger: state
  - entity_id:
      - binary_sensor.cloakroom_presence_occupancy
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: Absence
    alias: When someone leaves the cloakroom.
    trigger: state
  - event_type: timer.finished
    event_data:
      entity_id: timer.cloakroom_light
    id: Timer Done
    alias: When cloakroom timer runs down.
    enabled: true
    trigger: event
  - alias: When light level is low.
    entity_id:
      - sensor.cloakroom_presence_illuminance
    below: 30
    id: Low Light
    trigger: numeric_state
  - trigger: state
    entity_id:
      - binary_sensor.cloakroom_door
    from: "off"
    to: "on"
    id: Door Open
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Presence
              - Door Open
          - condition: state
            entity_id: binary_sensor.quiet_time_boys
            state: "off"
        sequence:
          - alias: Turn on extractor.
            action: light.turn_on
            target:
              entity_id:
                - light.cloakroom_switch_light_2
            data: {}
          - data: {}
            target:
              entity_id: timer.cloakroom_light
            action: timer.start
          - condition: or
            conditions:
              - condition: sun
                before: sunrise
                after: sunset
              - condition: numeric_state
                entity_id: sensor.cloakroom_presence_illuminance
                below: 30
          - alias: Turn on light.
            action: light.turn_on
            target:
              entity_id:
                - light.cloakroom_switch_light
            data: {}
        alias: When someone enters cloakroom outside of quite time.
      - conditions:
          - condition: trigger
            id:
              - Presence
              - Door Open
          - condition: state
            entity_id: binary_sensor.quiet_time_boys
            state: "on"
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: sensor.cloakroom_presence_illuminance
                below: 30
              - condition: sun
                before: sunrise
                after: sunset
        sequence:
          - action: light.turn_on
            target:
              entity_id:
                - light.cloakroom_switch_light
            data: {}
            alias: Turn on light only.
          - data: {}
            target:
              entity_id: timer.cloakroom_light
            action: timer.start
        alias: When someone enters cloakroom during quite time.
      - conditions:
          - condition: trigger
            id:
              - Absence
          - condition: state
            entity_id: timer.cloakroom_light
            state: idle
        sequence:
          - data: {}
            target:
              entity_id:
                - light.cloakroom_switch_light
            action: light.turn_off
            alias: Turn off the light.
          - condition: state
            entity_id: light.cloakroom_switch_light_2
            state: "on"
            alias: Check if the extractor is on.
          - data: {}
            target:
              entity_id:
                - light.cloakroom_switch_light_2
            action: light.turn_off
            alias: Turn off the extractor.
        alias: When someone leaves the cloakroom.
      - conditions:
          - condition: trigger
            id:
              - Timer Done
          - condition: state
            entity_id: binary_sensor.cloakroom_presence_occupancy
            state: "off"
        sequence:
          - if:
              - condition: state
                entity_id: binary_sensor.quiet_time_boys
                state: "off"
            then:
              - action: light.turn_off
                target:
                  entity_id: light.cloakroom_switch_light_2
                data: {}
              - if:
                  - condition: state
                    entity_id: light.cloakroom_switch_light
                    state: "on"
                then:
                  - action: light.turn_off
                    target:
                      entity_id: light.cloakroom_switch_light
                    data: {}
            else:
              - action: light.turn_off
                target:
                  entity_id: light.cloakroom_switch_light
                data: {}
        alias: When cloakroom timer runs down.
      - conditions:
          - condition: trigger
            id:
              - Low Light
          - condition: state
            entity_id: binary_sensor.cloakroom_occupied
            state: "on"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.cloakroom_switch_light
            data: {}
            alias: Turn on the light.
mode: restart
