############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   17/08/2023                         #
#   @automation     :   En-Suite Fan                       #
#   @description    :   Controls fan based on humidity     #
#                                                          #
#                                                          #
#   @version        :   1.0                                #
#   @modified       :                                      #
############################################################

alias: En-Suite Bathroom Fan On/Off with Humidity Level or Off with Timer
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.en_suite_temperature_and_humidity_humidity
    above: input_number.en_suite_fan_activate
    id: Humidity High
    alias: when En-Suite Bathroom humidity is above the Fan Activate threshold
  - platform: numeric_state
    entity_id: sensor.en_suite_temperature_and_humidity_humidity
    below: 65
    id: Humidity Normal
    alias: When En-Suite humidity is below 65%
  - platform: state
    entity_id:
      - binary_sensor.quiet_time
    id: Quiet Time
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.en_suite_bathroom_fan
    id: En-Suite Fan Off
    alias: En-Suite Fan off with timer
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Humidity High
          - condition: state
            entity_id: switch.en_suite_fan_switch
            state: "off"
          - condition: state
            entity_id: binary_sensor.quiet_time
            state: "off"
        sequence:
          - type: turn_on
            device_id: b5edcb03424d315e8e0842e735d916f7
            entity_id: switch.en_suite_fan_switch
            domain: switch
          - service: timer.start
            data: {}
            target:
              entity_id: timer.en_suite_bathroom_fan
      - conditions:
          - condition: trigger
            id:
              - Humidity Normal
              - En-Suite Fan Off
          - condition: state
            entity_id: switch.en_suite_fan_switch
            state: "on"
        sequence:
          - type: turn_off
            device_id: b5edcb03424d315e8e0842e735d916f7
            entity_id: switch.en_suite_fan_switch
            domain: switch
      - conditions:
          - condition: trigger
            id: Quiet Time
        sequence:
          - if:
              - condition: state
                entity_id: switch.en_suite_fan_switch
                state: "on"
            then:
              - type: turn_off
                device_id: b5edcb03424d315e8e0842e735d916f7
                entity_id: switch.en_suite_fan_switch
                domain: switch
      - conditions:
          - condition: trigger
            id: Quiet Time
        sequence:
          - if:
              - condition: state
                entity_id: switch.en_suite_fan_switch
                state: "off"
              - condition: numeric_state
                entity_id: sensor.en_suite_temperature_and_humidity_humidity
                above: 70
            then:
              - type: turn_on
                device_id: b5edcb03424d315e8e0842e735d916f7
                entity_id: switch.en_suite_fan_switch
                domain: switch
mode: single
