alias: FitBit Automations
description: ""
triggers:
  - entity_id:
      - sensor.sense_battery_level_3
    below: 20
    id: Low battery
    trigger: numeric_state
  - entity_id:
      - sensor.sense_battery_level_3
    above: 99.9
    id: Charged
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Low battery
        sequence:
          - action: script.text_notify_dave
            data:
              title: FITBIT ALERT
              message: Your FitBit battery is low. Please charge.
      - conditions:
          - condition: trigger
            id:
              - Charged
        sequence:
          - action: script.text_notify_dave
            data:
              title: FITBIT ALERT
              message: Your FitBit battery is charged.
mode: single
