alias: Garage Dehumdifier Water Tray Full
description: ""
triggers:
  - entity_id:
      - sensor.garage_dehumidifier_water_tray_full
    from: not_full
    to: full
    id: Full
    trigger: state
  - entity_id:
      - sensor.garage_dehumidifier_water_tray_full
    from: full
    to: not_full
    id: Not Full
    trigger: state
  - entity_id:
      - sensor.garage_thermometer_temperature
    below: sensor.garage_thermal_comfort_dew_point
    id: Rust Risk
    trigger: numeric_state
  - entity_id:
      - sensor.garage_thermometer_temperature
    above: 8
    id: Restart
    trigger: numeric_state
  - entity_id:
      - humidifier.garage_dehumidifier_2
    to: "off"
    id: "Off"
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Full
        sequence:
          - action: script.text_notify_dave
            data:
              message: |
                {{[ 'The garage dehumidifier is full',
                    'The garage rust prevention system has stalled',
                    'The garage humidity level is increasing exponentially']|random }}
              title: GARAGE DEHUMIDIFIER
            alias: Send a notification based on an input text helper
          - alias: Broadcast message outside quiet time
            if:
              - condition: state
                entity_id: input_boolean.audible_notifications
                state: "on"
            then:
              - action: input_boolean.turn_on
                target:
                  entity_id: input_boolean.announcement_playing
                data: {}
              - action: script.jarvis_speech_engine_v3_0
                data:
                  where: dave
                  type: announcement
                  message: >-
                    {{ [  'This is an important announcement for the man of the
                    house. The garage dehumidifier water tray is full. Please
                    empty it.',   
                          'I have detected a momentary increase in humidity in the garage. Perhaps the atmospheric water extraction device has extracted as much moisture as it can hold',   
                          'The weather girls have reported a rise in humidity and a fall in barometric pressure. While it is not raining men, perhaps the garage dehumidifier is full',   
                          'The garage rust prevention device has stalled. Unless you want your cars to disintegrate into a heap of iron oxide, might I suggest you take immediate action.'     
                        ]|random }}
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 15
                  milliseconds: 0
              - action: input_boolean.turn_off
                target:
                  entity_id:
                    - input_boolean.announcement_playing
                data: {}
          - action: light.turn_on
            data:
              rgb_color:
                - 133
                - 255
                - 255
              brightness: 10
            target:
              entity_id: light.kitchen_aura_lamp_2
          - action: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.garage_dehumidifier_full
      - conditions:
          - condition: trigger
            id:
              - Not Full
        sequence:
          - action: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.garage_dehumidifier_full
          - alias: Broadcast message outside quiet time
            if:
              - condition: state
                entity_id: input_boolean.audible_notifications
                state: "on"
            then:
              - action: input_boolean.turn_on
                target:
                  entity_id: input_boolean.announcement_playing
                data: {}
              - action: script.jarvis_speech_engine_v3_0
                data:
                  where: dave
                  type: announcement
                  message: >-
                    {{ [  'Well now. Whoever emptied the garage dehumidifier,
                    thank you.',   
                          'I have detected a slightly longer term reduction in humidity in the garage. Thankfully, its because the atmospheric water extraction device has once again commenced extracting moisture.',   
                          'The weather girls have reported a fall in humidity and a increase in barometric pressure. While it is not raining men, it is good to see the garage dehumidifier is empty once more',   
                          'The garage rust prevention device has recommenced operation. You have saved your cars from disintegrating into a heap of iron oxide.'     
                        ]|random }}
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 15
                  milliseconds: 0
              - action: input_boolean.turn_off
                target:
                  entity_id:
                    - input_boolean.announcement_playing
                data: {}
          - if:
              - condition: state
                entity_id: binary_sensor.morning
                state: "on"
                alias: If Morning
            then:
              - action: light.turn_on
                data:
                  effect: Morning
                  brightness_pct: 1
                target:
                  entity_id: light.kitchen_aura_lamp_2
            else:
              - if:
                  - condition: state
                    entity_id: binary_sensor.lunchtime
                    state: "on"
                    alias: If Lunchtime
                then:
                  - action: light.turn_on
                    data:
                      effect: Falling Petals
                      brightness_pct: 1
                    target:
                      entity_id: light.kitchen_aura_lamp_2
                else:
                  - if:
                      - condition: state
                        entity_id: binary_sensor.afternoon
                        state: "on"
                        alias: If Afternoon
                    then:
                      - action: light.turn_on
                        data:
                          effect: Forest
                          brightness_pct: 1
                        target:
                          entity_id: light.kitchen_aura_lamp_2
                    else:
                      - if:
                          - condition: state
                            entity_id: binary_sensor.dinner_time
                            state: "on"
                            alias: If Dinnertime
                        then:
                          - action: light.turn_on
                            data:
                              effect: Eating Dots
                              brightness_pct: 1
                            target:
                              entity_id: light.kitchen_aura_lamp_2
                        else:
                          - action: light.turn_on
                            target:
                              entity_id: light.kitchen_aura_lamp_2
                            data:
                              effect: Firefly
                              brightness_pct: 1
      - conditions:
          - condition: trigger
            id:
              - Rust Risk
        sequence:
          - action: script.text_notify_dave
            data:
              message: Risk of condensation in the garage
              title: RISK OF RUST FORMATION
      - conditions:
          - condition: trigger
            id:
              - Restart
          - condition: state
            entity_id: humidifier.garage_dehumidifier_2
            state: "off"
          - condition: numeric_state
            entity_id: sensor.garage_thermometer_humidity
            above: 60
        sequence:
          - action: humidifier.turn_on
            target:
              entity_id: humidifier.garage_dehumidifier_2
            data: {}
      - conditions:
          - condition: trigger
            id:
              - "Off"
          - condition: numeric_state
            entity_id: sensor.garage_thermometer_temperature
            below: 10
        sequence:
          - action: script.text_notify_dave
            data:
              title: DEHUMIDIFIER OFF
              message: The garage dehumdifier has turned off due to low temperature.
mode: restart
