############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   19/08/2023                         #
#   @automation     :   Garage Doors With Lights           #
#   @description    :                                      #
#                                                          #
#                                                          #
#   @version        :   1.02                               #
#   @modified       :                                      #
############################################################

alias: Garage Lights With Doors
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.garage_door_state
    to: Open
    id: Open
  - platform: state
    entity_id:
      - sensor.garage_door_state
    to: Closed
    id: Closed
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Open
            alias: Turn on lights when a door is opened
          - condition: state
            entity_id: light.garage_lights
            state: "off"
        sequence:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.garage_lights
      - conditions:
          - condition: trigger
            id:
              - Closed
          - condition: state
            entity_id: light.garage_lights
            state: "on"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.garage_lights
            data: {}
mode: single

