alias: Garage Lights With Doors
description: ""
mode: single
triggers:
  - entity_id:
      - sensor.garage_door_state
    to: Open
    id: Open
    trigger: state
  - entity_id:
      - sensor.garage_door_state
    to: Closed
    id: Closed
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Open
            alias: Turn on lights when a door is opened
          - condition: state
            entity_id: light.garage_lights
            state: "off"
        sequence:
          - action: light.turn_on
            data: {}
            target:
              entity_id: light.garage_lights
      - conditions:
          - condition: trigger
            id:
              - Closed
          - condition: state
            entity_id: light.garage_lights
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.garage_lights
            data: {}
