############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   19/08/2023                         #
#   @automation     :   Garage Doors With Lights           #
#   @description    :                                      #
#                                                          #
#                                                          #
#   @version        :   1.0                                #
#   @modified       :                                      #
############################################################

alias: Garage Lights With Doors
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garage_door_left_contact
      - binary_sensor.garage_door_right_contact
    from: "off"
    to: "on"
    id: Open
  - platform: state
    entity_id:
      - binary_sensor.garage_door_left_contact
      - binary_sensor.garage_door_right_contact
    from: "on"
    to: "off"
    id: Closed
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Open
            alias: Turn on lights when a door is opened
          - condition: state
            entity_id: light.garage_lights
            state: "off"
        sequence:
          - service: light.turn_on
            data: {}
            target:
              entity_id: light.garage_lights
      - conditions:
          - condition: trigger
            id:
              - Closed
          - condition: state
            entity_id: light.garage_lights
            state: "on"
        sequence:
          - if:
              - condition: state
                entity_id: binary_sensor.garage_door_left_contact
                state: "off"
            then:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.garage_lights
            alias: If left door also closed turn off the lights
          - if:
              - condition: state
                entity_id: binary_sensor.garage_door_right_contact
                state: "off"
            then:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.garage_lights
            alias: If right door also closed turn off lights
mode: single
