############################################################ 
#   @author         :   Dave Forrester                      #
#   @date           :   17/08/2023                          #
#   @automation     :   Get Battery Output Limit            #
#   @description    :   For charging EV overnight           #
#                                                           #
#                                                           #
#   @version        :   1.0                                 #
#   @modified       :                                       #
#############################################################

alias: Get Battery Output Limit
description: Send a notification asking if the battery output should be limited overnight
triggers:
  - at: "21:05:00"
    trigger: time
conditions: []
actions:
  - alias: Send a notification to my phone
    data:
      message: |
        Do you want to limit the battery output overnight?
      title: Battery Output Limit
      data:
        actions:
          - action: "YES"
            title: "Yes"
          - action: "NO"
            title: "No"
    action: notify.mobile_app_daves_samsung_galaxy
  - alias: Wait for a response
    wait_for_trigger:
      - event_type: mobile_app_notification_action
        event_data:
          action: "YES"
        trigger: event
      - event_type: mobile_app_notification_action
        event_data:
          action: "NO"
        trigger: event
    timeout:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
    continue_on_timeout: true
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ not wait.trigger }}"
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.allow_battery_output_limit
            data: {}
          - action: script.text_notify_dave
            data:
              title: BATTERY WILL BE LIMITED OVERNIGHT
              message: Please ensure you have set time slots.
        alias: If no response received limit battery
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == \"YES\" }}"
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.allow_battery_output_limit
            data: {}
          - action: script.text_notify_dave
            data:
              title: BATTERY WILL BE LIMITED OVERNIGHT
              message: Please ensure you have set time slots.
        alias: If response is YES limit battery
      - conditions:
          - condition: template
            value_template: "{{ wait.trigger.event.data.action == \"NO\" }}"
        sequence:
          - if:
              - condition: state
                entity_id: input_boolean.allow_battery_output_limit
                state: "on"
            then:
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.allow_battery_output_limit
                data: {}
            alias: If Battery Limit Master is on turn it off
          - action: script.text_notify_dave
            data:
              title: BATTERY WILL NOT BE LIMITED OVERNIGHT
              message: Please check no time slots are set.
        alias: If response is NO don't limit battery
mode: single

