alias: Greenhouse Heating Toggle
description: >-
  Turn on and off the greenhouse heater to keep the temperature above 3 degrees
  C
triggers:
  - entity_id:
      - sensor.greenhouse_thermometer_temperature
    below: 6
    id: Greenhouse Heater On
    trigger: numeric_state
  - entity_id:
      - sensor.greenhouse_thermometer_temperature
    above: 10
    id: Greenhouse Heater Off
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: Greenhouse Heater On
        sequence:
          - action: switch.turn_on
            data: {}
            target:
              entity_id:
                - switch.heater_greenhouse_s1
                - switch.heater_greenhouse_s2
      - conditions:
          - condition: trigger
            id: Greenhouse Heater Off
        sequence:
          - action: switch.turn_off
            data: {}
            target:
              entity_id:
                - switch.heater_greenhouse_s1
                - switch.heater_greenhouse_s2
mode: single
