alias: Guest Mode Audio Feedback
description: ""
triggers:
  - entity_id:
      - input_boolean.guest_mode
    from: "off"
    to: "on"
    trigger: state
actions:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.announcement_playing
    data: {}
  - action: script.jarvis_speech_engine_v3_0
    data:
      where: all
      type: announcement
      message: >
        {{ [ "Guest Mode has been enabled.", "I have switched the home to guest
        mode.", "I have enabled guest mode. ", "Guest Mode is on." ] | random }}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - action: input_boolean.turn_off
    target:
      entity_id:
        - input_boolean.announcement_playing
    data: {}
