alias: Home Battery Watch
description: Notify me if there is a problem with the home battery
triggers:
  - entity_id:
      - sensor.solaredge_b1_status
    to: B_STATUS_IDLE
    id: Home Battery Idle
    for:
      hours: 0
      minutes: 2
      seconds: 0
    trigger: state
  - entity_id:
      - sensor.solaredge_b1_status
    to: unavailable
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: Home Battery Unavailable
    trigger: state
  - entity_id:
      - sensor.solaredge_b1_status
    to: unknown
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: Home Battery Unknown
    trigger: state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: Home Battery Idle
          - condition: sun
            after: sunset
        sequence:
          - action: script.text_notify_dave
            data:
              message: The Home Battery is idle
              title: HOME BATTERY
            alias: Send a notification to Dave
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: Home Battery Unavailable
              - condition: trigger
                id: Home Battery Unknown
        sequence:
          - action: script.text_notify_dave
            data:
              message: There is a problem with the Home Battery
              title: HOME BATTERY
            alias: Send a notification to Dave
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.announcement_playing
            data: {}
          - action: script.jarvis_speech_engine_v3_0
            data:
              where: dave
              type: announcement
              message: >-
                There is a problem with the home battery. Can you please
                investigate immediately.
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
          - action: input_boolean.turn_off
            target:
              entity_id:
                - input_boolean.announcement_playing
            data: {}
mode: single
