alias: Hot Water, solar and gas
description: >-
  Turn on the immersion heater when the battery is full and solar export is
  high. Check later in the day and, if needed, heat water with gas.
triggers:
  - entity_id:
      - sensor.electricity_bill_today
    below: 0
    id: Activate
    trigger: numeric_state
    enabled: true
  - entity_id:
      - sensor.power_grid_export
    above: 2800
    id: Switch On
    for:
      hours: 0
      minutes: 0
      seconds: 20
    trigger: numeric_state
  - entity_id:
      - sensor.power_battery_load
    above: 500
    id: Switch Off
    for:
      hours: 0
      minutes: 0
      seconds: 20
    trigger: numeric_state
  - entity_id:
      - sensor.hot_water_energy_consumption_daily
    above: 6
    id: 6kWh Energy Used
    trigger: numeric_state
  - at: "16:00:00"
    id: Deactivate
    trigger: time
  - alias: Valkyrie off with Timer
    event_type: timer.finished
    event_data:
      entity_id: timer.solar_hot_water_heating
    id: Timer Done
    enabled: true
    trigger: event
  - at: "17:30:00"
    id: Time On
    trigger: time
  - at: "21:00:00"
    id: Last Check
    trigger: time
  - trigger: numeric_state
    entity_id:
      - sensor.battery_state_of_charge
    above: 99
    id: Battery Charged
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Activate
          - condition: sun
            after: sunrise
            before: sunset
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.allow_valkyrie_on
            data: {}
          - condition: numeric_state
            entity_id: sensor.power_grid_export
            above: 2500
          - action: light.turn_on
            target:
              entity_id: light.valkyrie_solar_hot_water
            data: {}
          - action: timer.start
            data: {}
            target:
              entity_id:
                - timer.solar_hot_water_heating
        alias: Activate solar water when electricity bill for the day hits zero
      - conditions:
          - condition: trigger
            id:
              - Switch On
          - condition: sun
            after: sunrise
            before: sunset
          - condition: state
            entity_id: input_boolean.allow_valkyrie_on
            state: "on"
          - condition: state
            entity_id: light.valkyrie_solar_hot_water
            state: "off"
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.valkyrie_solar_hot_water
            data: {}
          - action: timer.start
            data: {}
            target:
              entity_id:
                - timer.solar_hot_water_heating
      - conditions:
          - condition: trigger
            id: Switch Off
          - condition: state
            entity_id: light.valkyrie_solar_hot_water
            state: "on"
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.valkyrie_solar_hot_water
            data: {}
          - action: timer.pause
            data: {}
            target:
              entity_id:
                - timer.solar_hot_water_heating
      - conditions:
          - condition: trigger
            id:
              - Deactivate
              - Timer Done
              - 6kWh Energy Used
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.allow_valkyrie_on
            data: {}
          - if:
              - condition: template
                value_template: >-
                  {{ states('light.valkyrie_solar_hot_water') != 'unavailable'
                  }}
                alias: If Valkyrie is not unavailable
              - condition: state
                entity_id: light.valkyrie_solar_hot_water
                state: "on"
            then:
              - action: light.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: light.valkyrie_solar_hot_water
              - action: timer.cancel
                metadata: {}
                data: {}
                target:
                  entity_id: timer.solar_hot_water_heating
            alias: >-
              If Valkyrie is available and on, turn it off,  else wait until it
              becomes available then turn it off.
          - wait_for_trigger:
              - trigger: template
                value_template: "{{ is_state('light.valkyrie_solar_hot_water','on') }}"
            timeout:
              hours: 0
              minutes: 30
              seconds: 0
              milliseconds: 0
          - action: light.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: light.valkyrie_solar_hot_water
          - action: timer.cancel
            metadata: {}
            data: {}
            target:
              entity_id: timer.solar_hot_water_heating
      - conditions:
          - condition: trigger
            id:
              - Time On
          - condition: numeric_state
            entity_id: sensor.hot_water_energy_consumption_daily
            below: 2.5
        sequence:
          - action: tado.set_water_heater_timer
            target:
              entity_id: water_heater.hot_water
            data:
              time_period: "00:30:00"
      - conditions:
          - condition: trigger
            id:
              - Last Check
          - condition: numeric_state
            entity_id: sensor.hot_water_energy_consumption_daily
            below: 2.5
        sequence:
          - action: tado.set_water_heater_timer
            target:
              entity_id: water_heater.hot_water
            data:
              time_period: "00:30:00"
      - conditions:
          - condition: trigger
            id:
              - Battery Charged
          - condition: template
            value_template: >-
              {{ states('sensor.rolec_energy_consumption_daily')| float(0) > 5
              }}
            alias: If the car was charged overnight
          - condition: sun
            after: sunrise
            before: sunset
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.allow_valkyrie_on
            data: {}
          - condition: numeric_state
            entity_id: sensor.power_grid_export
            above: 2500
          - action: light.turn_on
            target:
              entity_id: light.valkyrie_solar_hot_water
            data: {}
          - action: timer.start
            data: {}
            target:
              entity_id:
                - timer.solar_hot_water_heating
        alias: >-
          Activate solar water when the battery is charged if the EV has also
          been charged overnight
mode: single
