alias: Kids Bathroom Lights with presence
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.jack_and_jill_presence_occupancy
    from: "off"
    to: "on"
    id: Light On
  - platform: state
    entity_id:
      - binary_sensor.jack_and_jill_presence_occupancy
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: Light Off
condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Light On
          - condition: time
            after: "08:00:00"
            before: "20:00:00"
          - condition: numeric_state
            entity_id: sensor.jack_and_jill_presence_illuminance_lux
            below: input_number.daytime_light_needed
        sequence:
          - service: light.turn_on
            data:
              color_temp: 200
              brightness: 64
            target:
              entity_id: light.kids_bathroom_light
      - conditions:
          - condition: trigger
            id:
              - Light On
          - condition: time
            after: "20:00:00"
            before: "08:00:00"
          - condition: numeric_state
            entity_id: sensor.jack_and_jill_presence_illuminance_lux
            below: input_number.daytime_light_needed
        sequence:
          - service: light.turn_on
            data:
              rgb_color:
                - 255
                - 248
                - 52
              brightness: 26
            target:
              entity_id: light.kids_bathroom_light
      - conditions:
          - condition: trigger
            id:
              - Light Off
          - condition: state
            entity_id: light.kids_bathroom_light
            state: "on"
        sequence:
          - if:
              - condition: time
                weekday:
                  - sun
                after: "17:30:00"
                before: "19:00:00"
            then:
              - delay:
                  hours: 0
                  minutes: 30
                  seconds: 0
                  milliseconds: 0
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.kids_bathroom_light
            else:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.kids_bathroom_light
mode: restart
