alias: Kids Bathroom Lights with presence
description: ""
triggers:
  - entity_id:
      - binary_sensor.jack_and_jill_presence_occupancy
    from: "off"
    to: "on"
    id: Light On
    trigger: state
  - entity_id:
      - binary_sensor.jack_and_jill_presence_occupancy
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 2
      seconds: 0
    id: Light Off
    trigger: state
  - at: "20:00:10"
    id: Dim on
    trigger: time
  - entity_id:
      - switch.jamie_bathroom_switch_left
      - switch.sean_bathroom_switch_right
    from: "off"
    to: "on"
    id: Lights to Max
    trigger: state
  - entity_id:
      - switch.jamie_bathroom_switch_left
      - switch.sean_bathroom_switch_right
    from: "on"
    to: "off"
    id: Lights to Presence
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Light On
          - condition: state
            entity_id: input_boolean.allow_kids_bathroom_lights_max
            state: "off"
          - condition: time
            after: "07:00:00"
            before: "20:00:00"
          - condition: numeric_state
            entity_id: sensor.jack_and_jill_presence_illuminance
            below: input_number.low_light_threshold
        sequence:
          - data:
              color_temp: 200
              brightness: 64
            target:
              entity_id: light.kids_bathroom_light
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - Light On
          - condition: state
            entity_id: input_boolean.allow_kids_bathroom_lights_max
            state: "off"
          - condition: time
            after: "20:00:00"
            before: "07:00:00"
          - condition: numeric_state
            entity_id: sensor.jack_and_jill_presence_illuminance
            below: input_number.low_light_threshold
        sequence:
          - data:
              rgb_color:
                - 255
                - 248
                - 52
              brightness: 26
            target:
              entity_id: light.kids_bathroom_light
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - Light Off
          - condition: state
            entity_id: light.kids_bathroom_light
            state: "on"
          - condition: state
            entity_id: input_boolean.allow_kids_bathroom_lights_max
            state: "off"
        sequence:
          - target:
              entity_id: light.kids_bathroom_light
            data: {}
            action: light.turn_off
      - conditions:
          - condition: trigger
            id:
              - Dim on
        sequence:
          - data:
              rgb_color:
                - 255
                - 248
                - 52
              brightness: 26
            target:
              entity_id: light.kids_bathroom_light
            action: light.turn_on
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - condition: state
            entity_id: binary_sensor.kids_bathroom_occupied
            state: "off"
          - target:
              entity_id: light.kids_bathroom_light
            data: {}
            action: light.turn_off
      - conditions:
          - condition: trigger
            id:
              - Lights to Max
        sequence:
          - target:
              entity_id: input_boolean.allow_kids_bathroom_lights_max
            data: {}
            action: input_boolean.turn_on
          - target:
              entity_id: light.kids_bathroom_light
            data:
              brightness: 255
              color_temp: 154
            action: light.turn_on
      - conditions:
          - condition: trigger
            id:
              - Lights to Presence
        sequence:
          - target:
              entity_id: input_boolean.allow_kids_bathroom_lights_max
            data: {}
            action: input_boolean.turn_off
          - target:
              entity_id: light.kids_bathroom_light
            data: {}
            action: light.turn_off
mode: restart
