alias: Letterbox
description: ""
mode: parallel
max: 10
triggers:
  - entity_id:
      - binary_sensor.letterbox_contact
    to: "off"
    from: "on"
    trigger: state
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.front_door_motion_detected
        state: "on"
      - condition: state
        entity_id: binary_sensor.front_door_person_detected
        state: "on"
actions:
  - data:
      message: You have post!
      title: POST!
    action: script.text_notify_parents
  - condition: state
    entity_id: input_boolean.audible_notifications
    state: "on"
  - if:
    - condition: state
      entity_id: binary_sensor.dave_home
      state: "on"
    then:
        - action: script.jarvis_speech_engine_v3_0
          data:
            where: dave
            type: announcement
            message: Youve got post.     
    else:
        - action: script.jarvis_speech_engine_v3_0
          data:
            where: gem
            type: announcement
            message: Youve got post.    
  - action: input_boolean.toggle
    target:
      entity_id: input_boolean.post
    data: {}
  - wait_for_trigger:
      - entity_id:
          - binary_sensor.family_home
        to: "off"
        from: "on"
        trigger: state
  - action: input_boolean.toggle
    target:
      entity_id: input_boolean.post
    data: {}
