############################################################ 
#   @author         :   Dave Forrester                      #
#   @date           :   17/08/2023                          #
#   @automation     :   Limit Home Battery Ouput            #
#   @description    :   Ensures EV doesn't drain home       #
#                       battery when charging EV overnight  #
#                                                           #
#                                                           #
#   @version        :   1.0                                 #
#   @modified       :                                       #
#############################################################

alias: Limit Battery Output
description: >-
  Limit the overnight output of the battery during high next day Agile pricing
  in Winter
triggers:
  - at: input_datetime.start_battery_output_limit
    id: Start of Slot 1
    trigger: time
  - at: input_datetime.end_battery_output_limit
    id: End of Slot 1
    trigger: time
  - at: input_datetime.start_battery_output_limit_slot_2
    id: Start of Slot 2
    trigger: time
  - at: input_datetime.end_battery_output_limit_slot_2
    id: End of Slot 2
    trigger: time
  - at: input_datetime.start_battery_output_limit_slot_3
    id: Start of Slot 3
    trigger: time
  - at: input_datetime.end_battery_output_limit_slot_3
    id: End of Slot 3
    trigger: time
  - at: input_datetime.start_battery_output_limit_slot_4
    id: Start of Slot 4
    trigger: time
  - at: input_datetime.end_battery_output_limit_slot_4
    id: End of Slot 4
    trigger: time
  - alias: When inverter resets
    entity_id:
      - switch.solaredge_i1_advanced_power_control
    from: unavailable
    to: "on"
    id: Inverter Reset
    trigger: state
conditions:
  - condition: template
    value_template: "{{ is_state('input_boolean.allow_battery_output_limit','on') }}"
    alias: Is Allow Battery Output Limit On?
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: Start of Slot 1
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_1
            state: "on"
        sequence:
          - data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id: End of Slot 1
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_1
            state: "on"
        sequence:
          - data:
              value: >-
                {{ states('input_number.default_battery_output_limit') |
                float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id: Start of Slot 2
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_2
            state: "on"
        sequence:
          - data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id: End of Slot 2
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_2
            state: "on"
        sequence:
          - data:
              value: >-
                {{ states('input_number.default_battery_output_limit') |
                float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id: Start of Slot 3
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_3
            state: "on"
        sequence:
          - data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id: End of Slot 3
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_3
            state: "on"
        sequence:
          - data:
              value: >-
                {{ states('input_number.default_battery_output_limit') |
                float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id: Start of Slot 4
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_4
            state: "on"
        sequence:
          - data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id: End of Slot 4
          - condition: state
            entity_id: input_boolean.battery_output_limit_slot_4
            state: "on"
        sequence:
          - data:
              value: >-
                {{ states('input_number.default_battery_output_limit') |
                float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
      - conditions:
          - condition: trigger
            id:
              - Inverter Reset
          - condition: time
            after: input_datetime.start_battery_output_limit
            before: input_datetime.end_battery_output_limit_slot_4
          - condition: numeric_state
            entity_id: number.solaredge_i1_storage_discharge_limit
            above: 100
          - condition: state
            entity_id: input_boolean.allow_battery_output_limit
            state: "on"
        sequence:
          - data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
            action: number.set_value
trace:
  stored_traces: 10
mode: single


