############################################################ 
#   @author         :   Dave Forrester                      #
#   @date           :   17/08/2023                          #
#   @automation     :   Limit Home Battery Ouput            #
#   @description    :   Ensures EV doesn't drain home       #
#                       battery when charging EV overnight  #
#                                                           #
#                                                           #
#   @version        :   1.0                                 #
#   @modified       :                                       #
#############################################################

alias: Limit Battery Output
description: Limit the output of the battery during overnight EV charging window
trigger:
  - platform: time
    at: input_datetime.start_battery_output_limit
    id: Start of Charge Period 1
  - platform: time
    at: input_datetime.end_battery_output_limit
    id: End of Charge Period 1
  - platform: time
    at: input_datetime.start_battery_output_limit_slot_2
    id: Start of Charge Period 2
  - platform: time
    at: input_datetime.end_battery_output_limit_slot_2
    id: End of Charge Period 2
  - platform: time
    at: input_datetime.start_battery_output_limit_slot_3
    id: Start of Charge Period 3
  - platform: time
    at: input_datetime.end_battery_output_limit_slot_3
    id: End of Charge Period 3
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: Start of Charge Period 1
          - condition: numeric_state
            entity_id: number.solaredge_i1_storage_discharge_limit
            above: >-
              input_number.desired_battery_output_limit_for_overnight_ev_charging
          - "{{ is_state('input_boolean.battery_output_limit_slot_1','on') }}"
        sequence:
          - service: number.set_value
            data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
      - conditions:
          - condition: trigger
            id: End of Charge Period 1
          - condition: numeric_state
            entity_id: number.solaredge_i1_storage_discharge_limit
            below: >-
              input_number.desired_battery_output_limit_for_overnight_ev_charging
          - "{{ is_state('input_boolean.battery_output_limit_slot_1','on') }}"
        sequence:
          - service: number.set_value
            data:
              value: >-
                {{ states('input_number.default_battery_output_limit') |
                float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
      - conditions:
          - condition: trigger
            id: Start of Charge Period 2
          - condition: numeric_state
            entity_id: number.solaredge_i1_storage_discharge_limit
            above: >-
              input_number.desired_battery_output_limit_for_overnight_ev_charging
          - "{{ is_state('input_boolean.battery_output_limit_slot_2','on') }}"
        sequence:
          - service: number.set_value
            data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
      - conditions:
          - condition: trigger
            id: End of Charge Period 2
          - condition: numeric_state
            entity_id: number.solaredge_i1_storage_discharge_limit
            below: >-
              input_number.desired_battery_output_limit_for_overnight_ev_charging
          - "{{ is_state('input_boolean.battery_output_limit_slot_2','on') }}"
        sequence:
          - service: number.set_value
            data:
              value: >-
                {{ states('input_number.default_battery_output_limit') |
                float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
      - conditions:
          - condition: trigger
            id: Start of Charge Period 3
          - condition: numeric_state
            entity_id: number.solaredge_i1_storage_discharge_limit
            above: >-
              input_number.desired_battery_output_limit_for_overnight_ev_charging
          - "{{ is_state('input_boolean.battery_output_limit_slot_3','on') }}"
        sequence:
          - service: number.set_value
            data:
              value: >-
                {{
                states('input_number.desired_battery_output_limit_for_overnight_ev_charging')
                | float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
      - conditions:
          - condition: trigger
            id: End of Charge Period 3
          - condition: numeric_state
            entity_id: number.solaredge_i1_storage_discharge_limit
            below: >-
              input_number.desired_battery_output_limit_for_overnight_ev_charging
          - "{{ is_state('input_boolean.battery_output_limit_slot_3','on') }}"
        sequence:
          - service: number.set_value
            data:
              value: >-
                {{ states('input_number.default_battery_output_limit') |
                float(0) }}
            target:
              entity_id: number.solaredge_i1_storage_discharge_limit
mode: single
