alias: List Daily Calendar Events
description: ""
triggers:
  - hours: /1
    trigger: time_pattern
conditions: []
actions:
  - action: calendar.get_events
    data:
      duration:
        hours: 24
        minutes: 0
        seconds: 0
    target:
      entity_id: calendar.forrester_events
    response_variable: calendar_response
  - event: calendar_poll
    event_data:
      calendar_response: "{{ calendar_response }}"
mode: single
