alias: List Daily Calendar Events
description: ""
trigger:
  - platform: time_pattern
    hours: /12
condition: []
action:
  - service: calendar.get_events
    data:
      duration:
        hours: 24
        minutes: 0
        seconds: 0
    target:
      entity_id: calendar.forrester_events
    response_variable: calendar_response
  - event: calendar_poll
    event_data:
      calendar_response: "{{ calendar_response }}"
mode: single
