alias: Night Lights and Reset
description: Turns on lights at dusk. Turn off all lights at bedtime and reset toggles
triggers:
  - entity_id:
      - binary_sensor.quiet_time_boys
    from: "on"
    to: "off"
    id: Camera LED On
    trigger: state
  - entity_id:
      - binary_sensor.quiet_time_boys
    from: "off"
    to: "on"
    id: Camera LED Off
    trigger: state
  - event: sunset
    offset: 0
    id: Sunset
    trigger: sun
  - event: sunrise
    offset: 0
    id: Sunrise
    trigger: sun
conditions:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Camera LED Off
        sequence:
          - target:
              entity_id:
                - switch.landing_camera_indicator_led
                - switch.jamie_indicator_led
                - switch.sean_indicator_led
                - switch.guest_bedroom_camera_indicator_led
            data: {}
            action: switch.toggle
      - conditions:
          - condition: trigger
            id:
              - Camera LED On
        sequence:
          - if:
              - condition: state
                entity_id: input_boolean.bst
                state: "on"
            then:
              - target:
                  entity_id:
                    - switch.landing_camera_indicator_led
                    - switch.jamie_indicator_led
                    - switch.sean_indicator_led
                    - switch.guest_bedroom_camera_indicator_led
                data: {}
                action: switch.toggle
            else:
              - delay:
                  hours: 1
                  minutes: 0
                  seconds: 0
                  milliseconds: 0
              - target:
                  entity_id:
                    - switch.landing_camera_indicator_led
                    - switch.jamie_indicator_led
                    - switch.sean_indicator_led
                    - switch.guest_bedroom_camera_indicator_led
                data: {}
                action: switch.toggle
      - conditions:
          - condition: trigger
            id:
              - Sunset
        sequence:
          - data: {}
            target:
              entity_id: switch.hallway_light_switch_2_left
            action: switch.turn_on
      - conditions:
          - condition: trigger
            id:
              - Sunrise
        sequence:
          - data: {}
            target:
              entity_id: switch.hallway_light_switch_2_left
            action: switch.turn_off
mode: parallel
max: 10
