alias: Notification Volume Normal
description: ""
triggers:
  - entity_id: binary_sensor.quiet_time_boys
    to: "off"
    trigger: state
conditions: []
actions:
  - action: media_player.volume_set
    data:
      entity_id:
        - media_player.kitchen_echo_show
        - media_player.living_room_pop
        - media_player.dining_room_pop
        - media_player.guest_bedroom_echo_dot
        - media_player.jamie_s_room_dot
        - media_player.sean_s_room_dot
        - media_player.office_pop
      volume_level: "{{ states('input_number.alexa_volume_level_announcements') | float(0) }}"
  - delay:
      hours: 0
      minutes: 28
      seconds: 0
      milliseconds: 0
  - action: media_player.volume_set
    data:
      entity_id:
        - media_player.main_bedroom_dot
      volume_level: "{{ states('input_number.alexa_volume_level_announcements') | float(0) }}"
  - action: media_player.volume_set
    data:
      volume_level: "{{ states('input_number.jarvis_volume_level_announcement') | float(0) }}"
    target:
      entity_id:
        - media_player.jarvis_downstairs_media_player
        - media_player.jarvis_main_bedroom_media_player
        - media_player.jarvis_kitchen_media_player
        - media_player.jarvis_jamie_media_player
mode: single
initial_state: true
