alias: Open Marauders' Map
description: >-
  Opens Marauders' Map when entering the office during Evening, Bedtime, or
  Overnight
triggers:
  - entity_id: binary_sensor.office_presence_sensor_occupancy
    to: "on"
    trigger: state
    id: Open
  - trigger: state
    entity_id:
      - binary_sensor.office_occupied
    from: "on"
    to: "off"
    id: Close
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Open
          - condition: template
            value_template: >-
              {{ states('input_select.part_of_day') in ['Evening', 'Bedtime',
              'Overnight'] }}
          - condition: state
            entity_id: binary_sensor.studio_code_server_running
            state: "off"
          - condition: state
            state: "off"
            entity_id: input_boolean.marauding_in_process
        sequence:
          - action: script.marauders_map_opens
            data: {}
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.marauding_in_process
            data: {}
      - conditions:
          - condition: trigger
            id:
              - Close
          - condition: template
            value_template: >-
              {{ states('input_select.part_of_day') in ['Evening', 'Bedtime',
              'Overnight'] }}
          - condition: state
            entity_id: binary_sensor.studio_code_server_running
            state: "off"
        sequence:
          - action: script.marauders_map_closes
            data: {}
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.marauding_in_process
            data: {}
