############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   17/08/2023                         #
#   @automation     :   Rolec EV Chargepoint Schedule      #
#   @description    :   Turns on chargepoint at cheap rate #
#                                                          #
#                                                          #
#   @version        :   1.01 (for Agile Import)            #
#   @modified       :   05/10/23                           #
############################################################

alias: Rolec EV Chargepoint schedule
description: Multiple Slots for Agile
trigger:
  - platform: time
    at: input_datetime.rolec_wallbox_on
    id: Rolec On 1
  - platform: time
    at: input_datetime.rolec_wallbox_off
    id: Rolec Off 1
  - platform: time
    at: input_datetime.rolec_wallbox_slot_2_on_at
    id: Rolec On 2
  - platform: time
    at: input_datetime.rolec_wallbox_slot_2_off_at
    id: Rolec Off 2
  - platform: time
    at: input_datetime.rolec_wallbox_slot_3_on_at
    id: Rolec On 3
  - platform: time
    at: input_datetime.rolec_wallbox_slot_3_off_at
    id: Rolec Off 3
  - platform: state
    entity_id:
      - switch.shelly1_c45bbe7867c7
    from: unavailable
    id: Rolec Available
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Rolec On 1
          - "{{ is_state('input_boolean.rolec_slot_1_active','on') }}"
        sequence:
          - type: turn_on
            device_id: e7eb66cdf13a7f21fc1052c0f676589e
            entity_id: switch.shelly1_c45bbe7867c7
            domain: switch
      - conditions:
          - condition: trigger
            id:
              - Rolec On 2
          - "{{ is_state('input_boolean.rolec_slot_2_active','on') }}"
        sequence:
          - type: turn_on
            device_id: e7eb66cdf13a7f21fc1052c0f676589e
            entity_id: switch.shelly1_c45bbe7867c7
            domain: switch
      - conditions:
          - condition: trigger
            id:
              - Rolec On 3
          - "{{ is_state('input_boolean.rolec_slot_3_active','on') }}"
        sequence:
          - type: turn_on
            device_id: e7eb66cdf13a7f21fc1052c0f676589e
            entity_id: switch.shelly1_c45bbe7867c7
            domain: switch
      - conditions:
          - condition: trigger
            id: Rolec Off 1
          - "{{ is_state('input_boolean.rolec_slot_1_active','on') }}"
        sequence:
          - type: turn_off
            device_id: e7eb66cdf13a7f21fc1052c0f676589e
            entity_id: switch.shelly1_c45bbe7867c7
            domain: switch
      - conditions:
          - condition: trigger
            id: Rolec Off 2
          - "{{ is_state('input_boolean.rolec_slot_2_active','on') }}"
        sequence:
          - type: turn_off
            device_id: e7eb66cdf13a7f21fc1052c0f676589e
            entity_id: switch.shelly1_c45bbe7867c7
            domain: switch
      - conditions:
          - condition: trigger
            id: Rolec Off 3
          - "{{ is_state('input_boolean.rolec_slot_3_active','on') }}"
        sequence:
          - type: turn_off
            device_id: e7eb66cdf13a7f21fc1052c0f676589e
            entity_id: switch.shelly1_c45bbe7867c7
            domain: switch
      - conditions:
          - condition: trigger
            id: Rolec Available
          - condition: or
            conditions:
              - condition: time
                after: input_datetime.rolec_wallbox_on
                before: input_datetime.rolec_wallbox_off
              - condition: time
                after: input_datetime.rolec_wallbox_slot_2_on_at
                before: input_datetime.rolec_wallbox_slot_2_off_at
              - condition: time
                after: input_datetime.rolec_wallbox_slot_3_on_at
                before: input_datetime.rolec_wallbox_slot_3_off_at
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.rolec_slot_1_active
                state: "on"
              - condition: state
                entity_id: input_boolean.rolec_slot_2_active
                state: "on"
              - condition: state
                entity_id: input_boolean.rolec_slot_3_active
                state: "on"
          - condition: state
            entity_id: switch.shelly1_c45bbe7867c7
            state: "off"
        sequence:
          - service: switch.turn_on
            data: {}
            target:
              entity_id: switch.shelly1_c45bbe7867c7
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: >-
                The Rolec was turned on because it became available during off
                peak
              title: ROLEC ON
            alias: Send a notification based on an input text helper
      - conditions:
          - condition: trigger
            id: Rolec Available
          - condition: or
            conditions:
              - condition: time
                after: input_datetime.rolec_wallbox_off
                before: input_datetime.rolec_wallbox_on
              - condition: time
                after: input_datetime.rolec_wallbox_slot_2_off_at
                before: input_datetime.rolec_wallbox_slot_2_on_at
              - condition: time
                after: input_datetime.rolec_wallbox_slot_3_off_at
                before: input_datetime.rolec_wallbox_slot_3_on_at
          - condition: or
            conditions:
              - condition: state
                entity_id: input_boolean.rolec_slot_1_active
                state: "off"
              - condition: state
                entity_id: input_boolean.rolec_slot_2_active
                state: "off"
              - condition: state
                entity_id: input_boolean.rolec_slot_3_active
                state: "off"
          - condition: state
            entity_id: switch.shelly1_c45bbe7867c7
            state: "on"
        sequence:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.shelly1_c45bbe7867c7
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: The Rolec was turned off because it was on outside off peak
              title: ROLEC OFF
            alias: Send a notification based on an input text helper
mode: single

