alias: Update Octopus Target Rate Length for Home Battery
description: ""
triggers:
  - entity_id:
      - input_number.home_battery_charge_length
    id: Home Battery
    trigger: state
conditions: []
actions:
  - target:
      entity_id: binary_sensor.octopus_energy_target_home_battery_charge
    data:
      target_hours: |
        "{{ states('input_number.home_battery_charge_length')}}"
    action: octopus_energy.update_target_config
  - action: target_timeframes.update_target_timeframe_config
    target:
      entity_id: binary_sensor.target_timeframes_octopus_energy_charge_home_battery
    data:
      target_hours: "{{ states('input_number.home_battery_charge_length')}}"
mode: single
