############################################################# 
#   @author         :   Dave Forrester                      #
#   @date           :   17/08/2023                          #
#   @automation     :   Update OpenUV                       #
#   @description    :   Refreshes UV API every 15 minutes   #
#                                                           #
#                                                           #
#   @version        :   1.0                                 #
#   @modified       :                                       #
#############################################################

alias: Update OpenUV
description: ""
trigger:
  - platform: time_pattern
    minutes: /15
condition:
  - condition: sun
    before: sunset
    after: sunrise
    before_offset: "+00:45:00"
  - condition: template
    value_template: |-
      {{ state_attr('automation.update_openuv', 'last_triggered') == None
         or (now() - state_attr('automation.update_openuv', 'last_triggered')
         ) >= timedelta(hours = 0, minutes = 40) }}
action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - binary_sensor.protection_window
        - sensor.current_uv_index
mode: single
