############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   17/08/2023                         #
#   @automation     :   Set volume forannouncements        #
#   @description    :   Set volume for announcments via    #
#                       number sliders.                    #
#                                                          #
#   @version        :   1.0                                #
#   @modified       :                                      #
############################################################ 

alias: Alexa Set Volume for Announcements
description: ""
trigger:
  - platform: state
    entity_id:
      - input_number.alexa_volume_level_announcements
    id: Alexa Set Volume Announcements
    alias: When Alexa Volume Level for Annoucements changes
condition: []
action:
  - service: media_player.volume_set
    target:
      entity_id:
        - media_player.dave_s_echo_pop
        - media_player.guest_bedroom_echo_dot
        - media_player.living_room_dot
        - media_player.kitchen_echo_show
        - media_player.main_bedroom_dot
        - media_player.dave_s_2nd_echo_pop_2
        - media_player.seans_room_dot
        - media_player.dave_s_2nd_echo_pop
    data:
      volume_level: "{{ states('input_number.alexa_volume_level_announcements') | float(0) }}"
mode: single

