############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   17/08/2023                         #
#   @automation     :   Lights Fade at Bedtime             #
#   @description    :   Uses a script with variables to    #
#                       fade out bed lights                #
#                                                          #
#   @version        :   1.0                                #
#   @modified       :                                      #
############################################################

alias: Lights Fade at Bedtime
description: ""
trigger:
  - platform: state
    entity_id:
      - switch.main_bedroom_dot_do_not_disturb_switch
    from: "off"
    to: "on"
condition: []
action:
  - service: script.stair_lights_fade_at_bedtime
    data: {}
mode: single
