############################################################ 
#   @author         :   Dave Forrester                     #
#   @date           :   19/08/2023                         #
#   @automation     :   Main Bedroom Lights with Presence  #
#   @description    :                                      #
#                                                          #
#                                                          #
#   @version        :   1.01                               #
#   @modified       :   16/09/2023                         #
############################################################

alias: Main Bedroom Lights with Presence
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.main_bedroom_fp2_presence_sensor_2
      - binary_sensor.main_bedroom_fp2_presence_sensor_3
    id: Lights On
    from: "off"
    to: "on"
  - platform: state
    entity_id:
      - binary_sensor.main_bedroom_fp2_presence_sensor_2
      - binary_sensor.main_bedroom_fp2_presence_sensor_3
    id: Lights Off
    from: "on"
    to: "off"
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: numeric_state
    entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
    below: input_number.low_light_threshold
    id: Low Light
  - platform: numeric_state
    entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
    id: Good Light
    above: input_number.upper_light_threshold_level
condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
  - condition: state
    entity_id: binary_sensor.lights_out
    state: "off"
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Lights On
          - condition: template
            value_template: "{{\"Daves\" in trigger.to_state.attributes.friendly_name }}"
            alias: Filter Dave's side of bed
          - condition: numeric_state
            entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
            below: input_number.low_light_threshold
          - condition: state
            entity_id: input_boolean.main_bedroom_bedside_lamps_active
            state: "on"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 5
              color_temp: 500
            target:
              entity_id: light.sonoff_1001f6d950
      - conditions:
          - condition: trigger
            id:
              - Lights On
          - condition: template
            value_template: "{{\"Gem\" in trigger.to_state.attributes.friendly_name }}"
            alias: Filter Gem's side of bed
          - condition: numeric_state
            entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
            below: input_number.low_light_threshold
          - condition: state
            entity_id: input_boolean.main_bedroom_bedside_lamps_active
            state: "on"
        sequence:
          - service: light.turn_on
            data:
              color_temp: 500
              brightness_pct: 5
            target:
              entity_id: light.sonoff_1001f6d982
      - conditions:
          - condition: trigger
            id:
              - Lights Off
          - condition: template
            value_template: "{{\"Daves\" in trigger.to_state.attributes.friendly_name }}"
            alias: Filter Dave's side of bed
          - condition: state
            state: "on"
            entity_id: light.sonoff_1001f6d950
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.sonoff_1001f6d950
      - conditions:
          - condition: trigger
            id:
              - Lights Off
          - condition: template
            value_template: "{{\"Gem\" in trigger.to_state.attributes.friendly_name }}"
            alias: Filter Gem's side of bed
          - condition: state
            state: "on"
            entity_id: light.sonoff_1001f6d982
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.sonoff_1001f6d982
      - conditions:
          - condition: trigger
            id:
              - Low Light
          - condition: state
            entity_id: input_boolean.room_occupied_main_bedroom
            state: "on"
          - condition: state
            entity_id: input_boolean.main_bedroom_bedside_lamps_active
            state: "on"
        sequence:
          - service: light.turn_on
            data:
              color_temp: 500
              brightness_pct: 5
            target:
              entity_id:
                - light.sonoff_1001f6d950
                - light.sonoff_1001f6d982
      - conditions:
          - condition: trigger
            id:
              - Good Light
          - condition: or
            conditions:
              - condition: state
                entity_id: light.sonoff_1001f6d950
                state: "on"
              - condition: state
                entity_id: light.sonoff_1001f6d982
                state: "on"
        sequence:
          - service: light.turn_off
            data: {}
            target:
              entity_id:
                - light.sonoff_1001f6d982
                - light.sonoff_1001f6d950
mode: restart

