alias: Peak/Cheap rate select for Go Utility meter
description: ""
trigger:
  - platform: time
    at: "00:30:00"
    variables:
      tariff: Off Peak
  - platform: time
    at: "04:30:00"
    variables:
      tariff: Peak
action:
  - service: select.select_option
    target:
      entity_id: select.octopus_go
    data:
      option: "{{ tariff }}"
mode: single
