alias: Solar Hot Water Toggle
description: >-
  Turn on the immersion heater when the battery is full and solar export is more
  than 1kW
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.electricity_bill_today
    below: 0
    id: Activate
  - platform: numeric_state
    entity_id:
      - sensor.power_grid_export
    above: 500
    id: Switch On
  - platform: numeric_state
    entity_id:
      - sensor.power_battery_load
    above: 1000
    id: Switch Off
  - platform: sun
    event: sunset
    offset: "-1:00:00"
    id: Deactivate
  - platform: time
    at: "17:00:00"
    id: Time On
  - platform: time
    at: "17:45:00"
    id: Time Off
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Activate
          - condition: sun
            after: sunrise
            before: sunset
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.allow_valkyrie_on
            data: {}
          - service: switch.turn_on
            target:
              entity_id: switch.valkyrie_solar_hot_water
            data: {}
      - conditions:
          - condition: trigger
            id:
              - Switch On
          - condition: sun
            after: sunrise
            before: sunset
          - condition: numeric_state
            entity_id: sensor.electricity_bill_today
            below: 0
          - condition: state
            entity_id: input_boolean.allow_valkyrie_on
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.valkyrie_solar_hot_water
            data: {}
      - conditions:
          - condition: trigger
            id: Switch Off
          - condition: state
            entity_id: switch.valkyrie_solar_hot_water
            state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.valkyrie_solar_hot_water
            data: {}
      - conditions:
          - condition: trigger
            id:
              - Deactivate
        sequence:
          - service: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.valkyrie_solar_hot_water
          - condition: state
            entity_id: switch.valkyrie_solar_hot_water
            state: "on"
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.allow_valkyrie_on
            data: {}
      - conditions:
          - condition: trigger
            id:
              - Time On
          - alias: Electricity Bill above -50p
            condition: numeric_state
            entity_id: sensor.electricity_bill_today
            above: -0.5
        sequence:
          - service: water_heater.set_operation_mode
            target:
              entity_id: water_heater.hot_water
            data:
              operation_mode: heat
      - conditions:
          - condition: trigger
            id:
              - Time Off
        sequence:
          - service: water_heater.set_operation_mode
            target:
              entity_id: water_heater.hot_water
            data:
              operation_mode: "off"
mode: single
