###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   02/19/2019
#   @package        :   Announcements
#   @description    :   Daily Announcements.
#
#   @modified by    :   Dave Forrester (Daverover66)
#   @date           :   01/09/2023
###############################################################################

###############################
# input_datetime - So the time report automation fires can be set in the UI
###############################
input_datetime:
  workday_wakeup_time:
    name: Workday Wakeup Time
    has_date: false
    has_time: true
  wakeup:
    name: Wakeup Time
    has_date: false
    has_time: true
  morning_report:
    name: Morning Report
    has_date: false
    has_time: true
  nightly_report:
    name: Nightly Report
    has_date: false
    has_time: true
  daily_report:
    name: Daily Report
    has_date: false
    has_time: true
  #audible_notification_on:
  #  name: Audible Notifications On
  #  has_date: false
  #  has_time: true
  #audible_notification_off:
  #  name: Audible Notifications Off
  #  has_date: false
  #  has_time: true

################################
# Announcment Automation - fires at the time of the above input_datetimes
################################
automation:
  #- id: 81bee5ee-6820-4626-aebf-3deb8de69e4d
  #  alias: Turn On Audible Notifications
  #  initial_state: true
  #  trigger:
  #    platform: template
  #    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.audible_notification_on', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  #  action:
  #    - service: input_boolean.turn_on
  #      entity_id: input_boolean.audible_notifications

  # Turn off audible notifications if they haven't been turned off yet.
  #- id: e0e9c774-6abe-42aa-bdab-32108bebb0e9
  #  alias: Turn Off Audible Notifications
  #  initial_state: true
  #  trigger:
  #    - platform: template
  #      value_template: "{{ states('sensor.time') == (state_attr('input_datetime.audible_notification_off', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  #  condition:
  #    - condition: state
  #      entity_id: input_boolean.audible_notifications
  #      state: "on"
  #  action:
  #    - service: input_boolean.turn_off
  #      entity_id: input_boolean.audible_notifications

  #################################
  #    School Morning Routine     #
  #################################
  - id: schoolday_morning_routine
    alias: School Morning Routine
    trigger:
      - platform: time
        at: input_datetime.get_ready_for_school_at
    condition:
      - condition: and
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.schoolday
                state: "on"
              - condition: state
                entity_id: binary_sensor.fridayschool
                state: "on"
          - condition: state
            entity_id: calendar.school_holidays
            state: "off"
    action:
      - service: script.status_annc
        data:
          where: living_room
          call_jetsons_chime: 1
          call_get_dressed: 1
      - delay:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0
      - service: script.status_annc
        data:
          where: living_room
          call_brush_teeth: 1
      - delay:
          hours: 0
          minutes: 0
          seconds: 10
          milliseconds: 0
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.living_room_tv
        enabled: true
      - service: media_player.turn_off
        data: {}
        target:
          entity_id: media_player.sky_q_main
        enabled: true
      - if:
          - condition: state
            entity_id: light.dreamview_g1_pro
            state: "on"
        then:
          - service: light.turn_off
            data: {}
            target:
              entity_id: light.dreamview_g1_pro
      - delay:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0 
      - service: script.status_annc
        data:
          where: "{{ states('sensor.room_audio') }}"
          call_late_school: 1
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.school_morning_announcement_played

  ###########################################
  #    School Pick Up Monday to Thursday    #
  ########################################### 
  - id: school_pick_up_mon_to_thurs
    alias: School Pick Up Monday to Thursday
    trigger:
      - platform: time
        at: input_datetime.school_pick_up_time_mon_to_thurs
    condition:
      - condition: state
        entity_id: binary_sensor.schoolday
        state: "on"
      - condition: state
        entity_id: calendar.school_holidays
        state: "off"
    action:
      - service: script.status_annc
        data:
          where: "{{ states('sensor.room_audio') }}"
          call_school_pick_up: 1
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.school_pick_up_announcement_played

  ###################################################
  #    School Morning Routine Friday                #
  ###################################################
  - id: school_pick_up_friday
    alias: School Pick Up Friday
    trigger:
      platform: time
      at: input_datetime.school_pick_up_time_friday
    condition:
    - condition: state
      entity_id: binary_sensor.fridayschool
      state: "on"
    - condition: state
      entity_id: calendar.school_holidays
      state: "off"
    action:
      - service: script.status_annc
        data:
          where: "{{ states('sensor.room_audio') }}"
          call_school_pick_up: 1 
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.school_pick_up_announcement_played 

  ###################################################
  #    Morning Briefing with Presence               #
  ###################################################
  - id: play_morning_briefing_annc
    alias: Play Morning Briefing
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_presence_sensor_presence_sensor_1
        from: "off"
        to: "on"
    condition:
      - condition: time
        after: '09:15:00'
        before: '10:15:00'
      - condition: state
        entity_id: input_boolean.morning_briefing_played
        state: 'off'
    action:
    - service: script.morning_briefing
      data:
        where: kitchen
        message: !include ../templates/speech/morning_briefing.yaml
    - service: input_boolean.turn_on
      entity_id: input_boolean.morning_briefing_played

  ###################################################
  #    Bedtime                                      #
  ###################################################
  - id: time_for_bed_annc
    alias: Time For Bed Announcement
    mode: single
    trigger:
      - platform: time
        at: "22:15:00"
    condition: []
    action:
      - service: script.status_annc
        data:
          where: living_room
          call_jetsons_chime: 1
          call_time_is: 1
          call_time_for_bed: 1
          
  ###########################################
  #    Boys Bedtime                         #
  ########################################### 
  - id: boys_bedtime_schoolnight
    alias: Boys Bedtime Schoolnight
    trigger:
      - platform: time 
        at: input_datetime.school_night
        id: School Bedtime
      - platform: time
        at: input_datetime.non_school_night
        id: Non School Bedtime
    action:
      - choose:
        - conditions:
          - condition: trigger
            id: School Bedtime
          - condition: state
            entity_id: binary_sensor.schoolnight
            state: "on"
          - condition: state
            entity_id: calendar.school_holidays
            state: "off"
         sequence:
           - service: script.status_annc
             data:
               where: living_room
               call_jetsons_chime: 1
               call_boys_time_for_bed: 1
           - service: input_boolean.turn_on
             data: {}
             target:
               entity_id: input_boolean.kids_bedtime_announcement_played
       - conditions:
           - condition: trigger
             id: Non School Bedtime
           - condition: or
             conditions:
               - condition: state
                 entity_id: binary_sensor.schoolnight
                 state: "off"
               - condition: state
                 entity_id: calendar.school_holidays
                 state: "on"
                 alias: Confirm School Holiday is on
          sequence:
            - service: script.status_annc
              data:
                where: living_room
                call_jetsons_chime: 1
                call_boys_time_for_bed: 1
            - service: input_boolean.turn_on
              data: {}
              target:
                entity_id: input_boolean.kids_bedtime_announcement_played
      

script:
  # welcome_briefing:
  #   sequence:
  #     - condition: state
  #       entity_id: input_boolean.welcome_home
  #       state: "on"
  #     - service: script.speech_engine
  #       data:
  #         where: "{{ states('sensor.room_audio') }}"
  #         message: !include ../templates/speech/welcome_briefing.yaml
  #     - delay: 00:02:00
  #     - service: input_boolean.turn_off
  #       entity_id: input_boolean.welcome_home

  #sundown_briefing:
  #  sequence:
  #    - service: script.speech_engine
  #      data:
  #        where: "{{ states('sensor.room__audio') }}"
  #        message: !include ../templates/speech/sundown_briefing.yaml
  #    - service: script.text_notify
  #      data:
  #        where: "all_android"
  #        message: "Sun is almost down. Time to call it a day."

  morning_briefing:
    sequence:
      - service: script.speech_engine
        data:
          where: kitchen
          message: !include ../templates/speech/morning_briefing.yaml

  #daily_briefing:
  #  sequence:
  #    - service: script.speech_engine
  #      data:
  #        where: "{{ states('sensor.room_audio') }}"
  #        message: !include ../templates/speech/daily_briefing.yaml

  #morning_wakeup_report:
  #  sequence:
  #    - service: media_player.play_media
  #      target:
  #        entity_id: media_player.main_bedroom_dot
  #      data:
  #       media_content_type: sound
  #        media_content_id: amzn_sfx_rooster_crow_01
  #    - service: script.speech_engine
  #      data:
  #        where: main_bedroom
  #        message: !include ../templates/speech/morning_wakeup_report.yaml

  #test_template_messages:
  # sequence:
  #    - service: script.speech_engine
  #      data:
  #        where: "{{ where }}"
  #        message: !include ../templates/speech/sundown_briefing.yaml
