################################################################################## 
#   @author                 :   Jeffrey Stone                                    #
#   @date                   :   11/4/2020                                        #
#   @package                :   audio.yaml                                       #
#   @description            :   Sends audible notifications to the right Alexa   # 
#                                                                                #
#   @modified by            :   Chris Heder (@chrisron95)                        #
#   @date                   :   05/12/2022                                       #    
#                                                                                #
#   @further modified by    :   Dave Forrester (@Daverover66)                    #
#   @date                   :   23/09/2023                                       #
##################################################################################

#################################################################################
# Media Player section for any media players you want to define. Most of these are setup via the integrations flow in the UI, 
# but if not you may need to modify the following section. 
# For more info on Media Players visit https://www.home-assistant.io/integrations/media_player/
# MODIFY this section as needed or comment it out completely if not needed.
#################################################################################

################################
# Media extractor is used for playing youtube audio. For more info ->https://www.home-assistant.io/integrations/media_extractor/
#
# If you have this enabled in another package or in your configuration.yaml comment out the line below
media_extractor:
  
###########################
#      Helpers            #
###########################

###########################
#     Datetime            #
###########################

input_datetime:
  last_time_alexa_called:
    name: Last Time Alexa Called
    has_date: true
    has_time: true
  announcement_delay:
    name: Announcement Delay
    has_date: false
    has_time: true
  good_morning:
    name: Good Morning
    has_date: false
    has_time: true
  good_night_routine:
    name: Good Night Routine
    has_date: false
    has_time: true
  morning_standby:
    name: Morning Standby
    has_date: false
    has_time: true

################################
#            Text              #
################################
input_text:
  room_with_alexa_presence:
    name: Room With Alexa Presence
   
#################################
#           Number              #
#################################

input_number:
  alexa_volume_level_default_all:
    name: Alexa Volume Level Default
    initial: 0.3
    min: 0
    max: 1
    step: 0.05
    mode: slider
    icon: mdi:volume-equal
  alexa_volume_level_announcements:
    name: Alexa Volume Level Announcements
    initial: 0.5
    min: 0
    max: 1
    step: 0.05
    mode: slider
    icon: mdi:volume-equal
  alexa_volume_level_high:
    name: Alexa Volume Level High
    initial: 1
    min: 0
    max: 1
    step: 0.05
    mode: slider
    icon: mdi:volume-equal
  alexa_volume_level_low:
    name: Alexa Volume Level Low
    initial: 0.2
    min: 0
    max: 1
    step: 0.05
    mode: slider
    icon: mdi:volume-equal

group:
  room_with_alexa_presence:
    name: Room With Alexa Presence
    icon: mdi:location-enter
    entities:
      - binary_sensor.living_room_fp2_presence_sensor_1
      - binary_sensor.kitchen_presence_sensor_presence_sensor_1
      - binary_sensor.dining_room_presence_sensor_occupancy
      - binary_sensor.main_bedroom_fp2_presence_sensor_1
      - binary_sensor.guest_bedroom_motion_occupancy
      - binary_sensor.seans_room_camera_cell_motion_detection
      - binary_sensor.jamie_s_room_cam_cell_motion_detection
      - binary_sensor.office_presence_sensor_occupancy

  boys_bedroom_echos:
    name: "Boys Bedroom Echos"
    icon: mdi:multimedia
    entities:
      - media_player.seans_room_dot
      - media_player.living_room_dot

  bedroom_echos:
    name: "Bedroom Echos"
    icon: mdi:multimedia
    entities:
      - media_player.main_bedroom_dot
      - media_player.guest_bedroom_echo_dot

#############################################
#                Automations                #
#############################################

automation:
  - id: a3739bb0-632d-4526-bf82-ee4e27b80882
    alias: Set Room With Alexa Presence
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.room_audio
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.room_with_alexa_presence
          value: "{{ states('sensor.room_audio') }}"
      - service: mqtt.publish
        data:
          topic: house/presence/current_room
          payload: "{{ states('sensor.room_audio') }}"
          retain: true
      - service: mqtt.publish
        data:
          topic: house/presence/backup_room
          payload: "{{ states('input_text.room_presence') }}"
          retain: true

  - id: 8a2711f5-a034-4df0-ba67-4b8f85ceaaee
    alias: Notification Volume Dim
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.quiet_time_boys
        to: "on"
    action:
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.kitchen_echo_show
            - media_player.dave_s_2nd_echo_pop
               # living room #
            - media_player.dave_s_echo_pop
               # dining room #
            - media_player.main_bedroom_dot
            - media_player.guest_bedroom_echo_dot
            - media_player.dave_s_2nd_echo_pop_2
              # office #
            - media_player.living_room_dot
              # jamies room #
            - media_player.seans_room_dot
          volume_level: "{{ states('input_number.alexa_volume_level_low') | float(0) }}"

  - id: d5fe0a64-9012-4446-b946-cbcafb2c0728
    alias: Notification Volume Normal
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.quiet_time_boys
        to: "off"
    action:
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.kitchen_echo_show
            - media_player.dave_s_2nd_echo_pop
               # living room #
            - media_player.dave_s_echo_pop
               # dining room #
            - media_player.main_bedroom_dot
            - media_player.guest_bedroom_echo_dot
            - media_player.dave_s_2nd_echo_pop_2
              # office #
            - media_player.living_room_dot
              # jamies room #
            - media_player.seans_room_dot
          volume_level: "{{ states('input_number.alexa_volume_level_announcements') | float(0) }}"

  - id: 28c0e7a6-4024-48c9-a422-8b8ffc3a86d1
    alias: Set Last Alexa Called Time
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - media_player.kitchen_echo_show
          - media_player.dave_s_2nd_echo_pop
               # living room #
          - media_player.dave_s_echo_pop
               # dining room #
          - media_player.main_bedroom_dot
          - media_player.guest_bedroom_echo_dot
          - media_player.dave_s_2nd_echo_pop_2
              # office #
          - media_player.living_room_dot
              # jamies room #
          - media_player.seans_room_dot
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.attributes.last_called_timestamp | float > trigger.from_state.attributes.last_called_timestamp | float }}" # Alexa has been triggered
    action:
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_time_alexa_called
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

  - id: alexa_set_default_volume
    alias: Alexa Set Default Volume
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_number.alexa_volume_level_default_all
        id: Alexa Set Volume Default
        alias: When Alexa Default Volume Changes
    condition: []
    action:
      - service: media_player.volume_set
        target:
          entity_id:
            - media_player.dave_s_echo_pop
            - media_player.guest_bedroom_echo_dot
            - media_player.living_room_dot
            - media_player.kitchen_echo_show
            - media_player.main_bedroom_dot
            - media_player.dave_s_2nd_echo_pop_2
            - media_player.seans_room_dot
            - media_player.dave_s_2nd_echo_pop
        data:
          volume_level: "{{ states('input_number.alexa_volume_level_default_all') | float(0) }}"

################################
# Scripts to handle audio
script:

  ################################
  # aws_s3_audio is meant to be used to play audio in your Amazon AWS S3 bucket.
  #
  #  It may not be needed if you only have Amazon Echo speakers as all audio can be fed to the alexa_voice
  #  script in the audio.yaml package.
  #
  # If you want to play audio files through Amazon Echo speakers, you'll need an Amazon AWS S3 bucket (aws.amazon.com) 
  # with audio files that have been through an audio converter such as v3.jovo.tech/audio-converter. These audio files must 
  # be publicly accessible so Home Assistant can use them in a notify.alexa_media service call.  Amazon Echo audio 
  # can only be played using the following service call:
  #
  # - service: notify.alexa_media
  #   data:
  #     target: media_player.your.echo.here
  #     data:
  #       type: tts
  #     message: <audio src='insert url to aws s3 file here'/>
  # 
  # Before using make sure you update as needed.
  # 
  # Alternatively, if you have the alexa_voice script in your audio.yaml package, you can use 
  # this script in the action section of your automation:
  # 
  # - service: script.alexa_voice
  #   data:
  #     where: kitchen
  #     message: >-
  #        <audio src='insert aws url here'/>
  #
  # aws_s3_audio:
  #  sequence:
  #  # Ensure that audible notifications are allowed. Comment out if not needed.
  #  - condition: state
  #    entity_id: input_boolean.audible_notifications
  #    state: 'on'
  #  # Ensure the family is home. If you are using a group to track the family, or a person just update as needed. Comment out if not needed.
  #  - condition: state
  #    entity_id: binary_sensor.family_home
  #    state: 'on'
  #  # This script plays the audio 
  #  - service: script.alexa_voice
  #      data:
  #        where: "{{ where }}"
  #        message: "{{ message }}"
        
  
  
  ################################
  # youtube_audio is meant to be used to play audio from well youtube. 
  # This script requires the media_extractor integration.
  # 
  # Before using make sure you update as needed.
  # 
  # To call this using in the action section of your automation:
  # 
  # - service: script.youtube_audio
  #   data:
  #     speaker: main
  #     volume: .5
  #     media: https://www.youtube.com/watch?v=pVeX4C9B1Lk
  #
  youtube_audio:
    sequence:
    # Ensure that audible notifications are allowed. Comment out if not needed.
    - condition: state
      entity_id: input_boolean.audible_notifications
      state: 'on'
    # Ensure the family is home. If you are using a group to track the family, or a person just update as needed. Comment out if not needed.
    - condition: state
      entity_id: binary_sensor.family_home
      state: 'on'
    # This sets the voume via a parameter when the script is called, and should be a value between .1 and 1.0
    - service: media_player.volume_set
      data:
        entity_id: >
          {% set who = speaker %}
          {% if who == 'kitchen' %}
            media_player.kitchen_display
          {% elif who == 'theater' %}
            media_player.theater_speaker
          {% elif who == 'croft' %}
            media_player.croft_speaker
          {% elif who in ['skylar_bedroom', 'skylars_bedroom'] %}
            media_player.skylars_bedroom_speaker
          {% elif who == 'master_bedroom' %}
            media_player.master_bedroom_speaker
          {% elif who in ['studio', 'studio_speaker', 'media_player.studio_speaker'] %}
            media_player.studio_speaker
          {% elif who == 'main' %}
            media_player.ha_blue
          {% else %}
            {% if states.input_boolean.audible_notifications.state == 'on' %}
            media_player.ha_blue
            {% else %}
            media_player.kitchen_display
            {% endif %}
          {% endif %}
        volume_level: >
          {{ volume }}
    # This tells it to play the media and is set when the script is called.
    #  media_content_type: video/Youtube
    - service: media_extractor.play_media
      data:
        entity_id: >
          {% set who = speaker %}
          {% if who == 'kitchen' %}
            media_player.kitchen_display
          {% elif who == 'theater' %}
            media_player.theater_speaker
          {% elif who == 'croft' %}
            media_player.croft_speaker
          {% elif who in ['skylar_bedroom', 'skylars_bedroom'] %}
            media_player.skylars_bedroom_speaker
          {% elif who == 'master_bedroom' %}
            media_player.master_bedroom_speaker
          {% elif who in ['studio', 'studio_speaker', 'media_player.studio_speaker'] %}
            media_player.studio_speaker
          {% elif who == 'main' %}
            media_player.ha_blue
          {% else %}
            {% if states.input_boolean.audible_notifications.state == 'on' %}
            media_player.ha_blue
            {% else %}
            media_player.kitchen_display
            {% endif %}
          {% endif %}
        media_content_type: music
        media_content_id: >
          {{ media }}


############################################
#               Sensors                    #
############################################

mqtt:
  sensor:
    - name: "Room With Alexa Presence"
      state_topic: "house/presence/current_room"
    - name: "Room Presence"
      state_topic: "house/presence/backup_room

template:
  ### Room audio for Alexa ###
  - sensor:
      - name: "Room Audio"
        unique_id: room_audio  
        state: |-
          {%- set last_alexa_called_seconds = (now() - as_local(states.media_player | rejectattr('object_id','match', '(sky_q|toshiba|chromecast|living_room_tv)') | selectattr('attributes.last_called','eq',True) | map(attribute='last_updated') | first)).seconds -%}
          {%- if last_alexa_called_seconds <= 60 %} 
            {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
          {% elif expand('group.room_with_alexa_presence') | selectattr('state', 'eq', 'on') | list | count >= 1 %}
            {% set sensor = expand('group.room_with_alexa_presence') | selectattr('state', 'eq', 'on') | sort(attribute='last_changed') | last %}
              {% if is_state('binary_sensor.quiet_time_boys','on') %}
                {% if sensor.name == 'Main Bedroom All Areas' %}
                  main_bedroom_dot
                {% else %}
                  dave_s_2nd_echo_pop
                {%- endif %}
              {% else %}
                {% if sensor.name == 'Living Room All Areas' %}
                  dave_s_2nd_echo_pop
                {% elif sensor.name == 'Main Bedroom All Areas' %}
                  main_bedroom_dot
                {% elif sensor.name == 'Dining Room Presence Sensor Motion' %}  
                  dave_s_echo_pop
                {% elif sensor.name == 'Guest Bedroom Motion Occupancy' %}
                  guest_bedroom_echo_dot
                {% elif sensor.name == 'Office Presence Sensor Motion' %}
                  {% if is_state('input_boolean.gem_gone_out_to_office','off') %}
                    guest_bedroom_echo_dot
                  {% else %}
                    dave_s_2nd_echo_pop_2 
                  {%- endif %}
                {% elif sensor.name == 'Seans Room Camera Cell Motion Detection' %}
                  seans_room_dot
                {% elif sensor.name == "Jamie's Room Cam Cell Motion Detection" %}
                  living_room_dot
                {% elif sensor.name == 'Kitchen Presence Sensor all areas' %}
                  kitchen_echo_show                     
                {%- endif %}
             {%- endif %}
          {% elif is_state('media_player.sky_q_main', 'on') %}
            dave_s_2nd_echo_pop
          {% elif is_state('media_player.sky_q_kitchen_mini_2', 'on') %}
            kitchen_echo_show
          {% else %}
            {{ states('sensor.room_presence') }}        
          {% endif %}
