################################################################################## 
#   @author                 :   Jeffrey Stone                                    #
#   @date                   :   11/4/2020                                        #
#   @package                :   audio.yaml                                       #
#   @description            :   Sends audible notifications to the right Alexa   # 
#                                                                                #
#   @modified by            :   Chris Heder (@chrisron95)                        #
#   @date                   :   05/12/2022                                       #    
#                                                                                #
#   @further modified by    :   Dave Forrester (@Daverover66)                    #
#   @date                   :   12/09/2023                                       #
##################################################################################

#################################################################################
# Media Player section for any media players you want to define. Most of these are setup via the integrations flow in the UI, 
# but if not you may need to modify the following section. 
# For more info on Media Players visit https://www.home-assistant.io/integrations/media_player/
# MODIFY this section as needed or comment it out completely if not needed.
#################################################################################
  
############################
#         Helpers          #
############################

input_select:
  echo_voice:
    name: Echo voice
    options:
      - Brian
      - Emma
      - Amy
      - Joanna
      - Justin
      - Matthew
      - Sally 
    initial: Brian

  jarvis_voice:
    name: Jarvis Voice 
    options:
      - LibbyNeural 
      - AbbiNeural 
      - AlfieNeural 
      - BellaNeural 
      - ElliotNeural 
      - EthanNeural 
      - HollieNeural 
      - MaisieNeural 
      - NoahNeural 
      - OliverNeural 
      - OliviaNeural 
      - RyanNeural 
      - SoniaNeural 
      - ThomasNeural 

  jarvis_language:
    name: Jarvis Language
    options:
      - en-GB 
      - en-IE 
      - en-CA
      - en-US 
      - en-AU 
      


############################
#         Datetime         #
############################

input_datetime:
  last_time_alexa_called:
    name: Last Time Alexa Called
    has_date: true
    has_time: true
  announcement_delay:
    name: Announcement Delay
    has_date: false
    has_time: true
  good_morning:
    name: Good Morning
    has_date: false
    has_time: true
  good_night_routine:
    name: Good Night Routine
    has_date: false
    has_time: true
  morning_standby:
    name: Morning Standby
    has_date: false
    has_time: true

#############################
#         Text              #
#############################

input_text:
  room_with_alexa_presence:
    name: Room With Alexa Presence

#############################
#        Number             #
#############################

input_number:
  alexa_volume_level_default_all:
    name: Alexa Volume Level Default
    initial: 0.3
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal
  alexa_volume_level_announcements:
    name: Alexa Volume Level Announcements
    initial: 0.4
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal
  alexa_volume_level_high:
    name: Alexa Volume Level High
    initial: 1
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal
  alexa_volume_level_low:
    name: Alexa Volume Level Low
    initial: 0.2
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal
  jarvis_volume_level_default:
    name: Jarvis Volume Level Default 
    initial: 0.7
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal
  jarvis_volume_level_announcement:
    name: Jarvis Volume Level Announcement 
    initial: 0.7
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal
  jarvis_volume_level_high:
    name: Jarvis Volume Level High
    initial: 1.0
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal
  jarvis_volume_level_low:
    name: Jarvis Volume Level Low
    initial: 0.4
    min: 0
    max: 1
    step: 0.05
    mode: box 
    icon: mdi:volume-equal

############################
#        Groups            #
############################

group:
  room_with_alexa_presence:
    name: Room With Alexa Presence
    icon: mdi:location-enter
    entities:
      - binary_sensor.living_room_fp2_presence_sensor_1
      - binary_sensor.kitchen_presence_sensor_presence_sensor_1
      - binary_sensor.dining_room_presence_sensor_occupancy
      - binary_sensor.main_bedroom_fp2_presence_sensor_1
      - binary_sensor.guest_bedroom_motion_occupancy
      - binary_sensor.office_presence_sensor_occupancy
      - binary_sensor.upper_landing_presence_occupancy
      - binary_sensor.lower_landing_motion_occupancy
      - binary_sensor.main_bathroom_presence_occupancy
      - binary_sensor.jack_and_jill_presence_occupancy
      - binary_sensor.cloakroom_presence_occupancy 
      - binary_sensor.hallway_presence_occupancy
      - binary_sensor.hallway_presence_2_occupancy
      - binary_sensor.sean_room_presence_occupancy
      - binary_sensor.jamie_room_presence_occupancy
      - binary_sensor.utility_room_presence_2_occupancy

  boys_bedroom_echos:
    name: "Boys Bedroom Echos"
    icon: mdi:multimedia
    entities:
      - media_player.sean_s_room_dot
      - media_player.jamie_s_room_dot

  bedroom_echos:
    name: "Bedroom Echos"
    icon: mdi:multimedia
    entities:
      - media_player.main_bedroom_dot
      - media_player.guest_bedroom_echo_dot

############################
#        Automations       #
############################
      
automation:
  - id: a3739bb0-632d-4526-bf82-ee4e27b80882
    alias: Set Room With Alexa Presence
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.room_audio
    action:
      - action: input_text.set_value
        data:
          entity_id: input_text.room_with_alexa_presence
          value: "{{ states('sensor.room_audio') }}"
      - action: mqtt.publish
        data:
          topic: house/presence/current_room
          payload: "{{ states('sensor.room_audio') }}"
          retain: true
      - action: mqtt.publish
        data:
          topic: house/presence/backup_room
          payload: "{{ states('input_text.room_presence') }}"
          retain: true
  ###################### migrated to UI 05/03/2025 ############# 
  # - id: alexa_set_default_volume
  #   alias: Alexa Set Default Volume
  #   description: ""
  #   mode: single
  #   initial_state: true
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - input_number.alexa_volume_level_default_all
  #   condition: []
  #   action:
  #     - action: media_player.volume_set
  #       target:
  #         entity_id:
  #           - media_player.living_room_pop 
  #           - media_player.dining_room_pop
  #           - media_player.kitchen_echo_show
  #           - media_player.main_bedroom_dot
  #           - media_player.guest_bedroom_echo_dot
  #           - media_player.jamie_s_room_dot
  #           - media_player.sean_s_room_dot
  #           - media_player.office_pop
  #       data:
  #         volume_level: "{{ states('input_number.alexa_volume_level_default_all') | float(0) }}"




  - id: 28c0e7a6-4024-48c9-a422-8b8ffc3a86d1
    alias: Set Last Alexa Called Time
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - media_player.kitchen_echo_show
          - media_player.living_room_pop 
              # living room #
          - media_player.dining_room_pop
              # dining room #
          - media_player.main_bedroom_dot
          - media_player.guest_bedroom_echo_dot
          - media_player.office_pop 
              # office #
          - media_player.jamie_s_room_dot 
              # jamies room #
          - media_player.sean_s_room_dot
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.attributes.last_called_timestamp | float > trigger.from_state.attributes.last_called_timestamp | float }}" # Alexa has been triggered
    action:
      - action: input_datetime.set_datetime
        target:
          entity_id: input_datetime.last_time_alexa_called
        data:
          datetime: "{{ now().strftime('%Y-%m-%d %H:%M:%S') }}"

#####################
#       Sensors     #
#####################

mqtt:
  sensor:
    - name: "Room With Alexa Presence"
      state_topic: "house/presence/current_room"
    - name: "Room Presence"
      state_topic: "house/presence/backup_room"

template:

  ### This one has last called Alexa ### 
  - sensor:
      - name: "Room Audio"
        icon: mdi:account-voice 
        unique_id: room_audio
        state: |-
          {%- set last_alexa_called_seconds = (now() - as_local(states.media_player | rejectattr('object_id','match', '(sky_q|toshiba|chromecast|living_room_tv)') | selectattr('attributes.last_called','eq',True) | map(attribute='last_updated') | first)).seconds -%}
          {%- if last_alexa_called_seconds <= 60 %} 
            {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
          {% elif expand('group.room_with_alexa_presence') | selectattr('state', 'eq', 'on') | list | count >= 1 %}
          {% set sensor = expand('group.room_with_alexa_presence') | selectattr('state', 'eq', 'on') | sort(attribute='last_changed') | last %}
            {% if is_state('binary_sensor.quiet_time_boys','on') %}
              {% if sensor.name == 'Living Room All Areas' or is_state('media_player.sky_q_main', 'playing') %}
                living_room_pop 
              {% elif sensor.name == 'Kitchen Presence Sensor all areas' or is_state('media_player.sky_q_kitchen_mini_2', 'playing') %}
                kitchen_echo_show
              {% else %}
                main_bedroom_dot
              {%- endif %}
            {% elif sensor.name == 'Living Room All Areas' and is_state('media_player.sky_q_main', 'playing') %}
              living_room_pop 
            {% elif sensor.name == 'Kitchen Presence Sensor all areas' and is_state('media_player.sky_q_kitchen_mini_2', 'playing') %}
              kitchen_echo_show
            {% elif sensor.name == 'Living Room All Areas' %}
              living_room_pop 
            {% elif sensor.name == 'Main Bedroom All Areas' or is_state('media_player.32_sharp_roku_tv','o') %}
              main_bedroom_dot
            {% elif sensor.name == 'Dining Room Presence Sensor Motion' %}  
              dining_room_pop 
            {% elif sensor.name == 'Guest Bedroom Motion Occupancy' or is_state('media_player.sky_q_kitchen_mini', 'playing')%}
              guest_bedroom_echo_dot
            {% elif sensor.name == 'Office Presence Sensor Motion' %}
                {% if is_state('input_boolean.gem_gone_out_to_office','off') %}
                  guest_bedroom_echo_dot
                {% else %}
                  office_pop  
                {%- endif %}
            {% elif sensor.name == 'Sean Room Presence Motion' %}
              sean_s_room_dot
            {% elif sensor.name == "Jamie Room Presence Motion" %}
              jamie_s_room_dot
            {% elif sensor.name == 'Kitchen Presence Sensor all areas' %}
              kitchen_echo_show
            {% elif sensor.name == 'Hallway Presence Motion' %}
              kitchen_echo_show  
            {% elif sensor.name == 'Upper Landing Presence Motion' %}
              main_bedroom_dot 
            {% elif sensor.name == 'Lower Landing Motion Motion' %}
              kitchen_echo_show  
            {% elif sensor.name == 'Main Bathroom Presence Motion' %}
              guest_bedroom_echo_dot 
            {% elif sensor.name == 'Jack and Jill Presence Motion' %}
              sean_s_room_dot 
            {% elif sensor.name == 'Cloakroom Presence Motion' %}
              kitchen_echo_show 
            {% else %}
              living_room_pop 
            {%- endif %}
          {% else %}
            living_room_pop 
          {% endif %}

  ### Development sensor for room audio  ### 
  - sensor:
      - name: "Room Audio Dev"
        unique_id: room_audio_dev 
        state: |-
          {%- set last_alexa_called_seconds = (now() - as_local(states.media_player | rejectattr('object_id','match', '(sky_q|toshiba|chromecast|living_room_tv)') | selectattr('attributes.last_called','eq',True) | map(attribute='last_updated') | first)).seconds -%}
          {%- if last_alexa_called_seconds <= 60 %} 
            {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
          {% elif expand('group.room_with_alexa_presence') | selectattr('state', 'eq', 'on') | list | count >= 1 %}
          {% set sensor = expand('group.room_with_alexa_presence') | selectattr('state', 'eq', 'on') | sort(attribute='last_changed') | last %}
            {% if is_state('binary_sensor.quiet_time_boys','on') %}
              {% if sensor.name == 'Living Room All Areas' or is_state('media_player.sky_q_main', 'playing') %}
                dave_s_2nd_echo_pop
              {% elif sensor.name == 'Kitchen Presence Sensor all areas' or is_state('media_player.sky_q_kitchen_mini_2', 'playing') %}
                kitchen_echo_show
              {% else %}
                main_bedroom_dot
              {%- endif %}
            {% elif sensor.name == 'Living Room All Areas' and is_state('media_player.sky_q_main', 'playing') %}
              living_room_pop
            {% elif sensor.name == 'Kitchen Presence Sensor all areas' and is_state('media_player.sky_q_kitchen_mini_2', 'playing') %}
              kitchen_echo_show
            {% elif sensor.name == 'Living Room All Areas' %}
              living_room_pop 
            {% elif sensor.name == 'Main Bedroom All Areas' or is_state('media_player.32_sharp_roku_tv','o') %}
              main_bedroom_dot
            {% elif sensor.name == 'Dining Room Presence Sensor Motion' %}  
              dining_room_pop 
            {% elif sensor.name == 'Guest Bedroom Motion Occupancy' or is_state('media_player.sky_q_kitchen_mini', 'playing')%}
              guest_bedroom_echo_dot
            {% elif sensor.name == 'Office Presence Sensor Motion' %}
                {% if is_state('input_boolean.gem_gone_out_to_office','off') %}
                  guest_bedroom_echo_dot
                {% else %}
                  officee_pop 
                {%- endif %}
            {% elif 'Kitchen' or 'Hallway' or 'Cloakroom' or 'Lower' in sensor.name %}
              kitchen_echo_show
            {% elif sensor.name == 'Sean Room Presence Motion' %}
              sean_s_room_dot
            {% elif sensor.name == "Jamie Room Presence Motion" %}
              jamie_s_room_dot
            {% elif sensor.name == 'Upper Landing Presence Motion' %}
              main_bedroom_dot 
            {% elif sensor.name == 'Main Bathroom Presence Motion' %}
              guest_bedroom_echo_dot 
            {% elif sensor.name == 'Jack and Jill Presence Motion' %}
              sean_s_room_dot 
            {% else %}
              living_room_pop 
            {%- endif %}
          {% else %}
            living_room_pop 
          {% endif %}
