###############################################################################
#   @author         :   Dave Forrester (@Daverover66)
#   @date           :   25/09/2023
#   @package        :   Guest Bedroom
#   @description    :   All Spare Room config
#
#   @modified by    :   Dave Forrester
#   @date           :   10/10/2023
###############################################################################

###########################
#     Helpers             #
###########################

###########################
#      Toggle             #
###########################

input_boolean:
  guest_bedroom_bedside_lamps_active:
    name: Guest Bedroom Bedside Lamps Active
    icon: mdi:lamp
  
  
###########################
#     Automations         #
###########################
automation:

###########################
#     Bedside Lamps       #
###########################
  - id: guest_bedroom_lights_with_presence
    alias: Guest Bedroom Lights with presence
    description: ""
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.guest_bedroom_motion_occupancy
          - binary_sensor.guest_bedroom_camera_cell_motion_detection
        from: "off"
        to: "on"
        id: Light on
      - platform: state
        entity_id:
          - binary_sensor.guest_bedroom_motion_occupancy
          - binary_sensor.guest_bedroom_camera_cell_motion_detection
        from: "on"
        to: "off"
        id: Light off
        for:
          hours: 0
          minutes: 1
          seconds: 0
      - platform: numeric_state
        entity_id: sensor.upstairs_light_level
        below: input_number.low_light_threshold
        id: Low Light
      - platform: numeric_state
        entity_id: sensor.upstairs_light_level
        id: Good Light
       above: input_number.upper_light_threshold_level
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: Light on
              - condition: state
                entity_id: binary_sensor.lights_out
                state: "off"
              - condition: numeric_state
                entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
                below: input_number.low_light_threshold
              - condition: state
                entity_id: input_boolean.guest_bedroom_bedside_lamps_active
                state: "on"
            sequence:
              - service: light.turn_on
                data:
                  color_temp: 500
                  brightness_pct: 5
                target:
                  entity_id: light.guest_bedroom_bedside_lamp_left
              - service: light.turn_on
                data:
                  color_temp: 500
                  brightness_pct: 5
                target:
                  entity_id:
                    - light.guest_bedroom_bedside_lamp_right
          - conditions:
              - condition: trigger
                id: Light off
              - condition: state
                entity_id: light.guest_bedroom_bedside_lamp_left
                state: "on"
              - condition: state
                entity_id: light.guest_bedroom_bedside_lamp_right
                state: "on"
             sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.guest_bedroom_bedside_lamp_left
                    - light.guest_bedroom_bedside_lamp_right
          - conditions:
              - condition: trigger
                id:
                  - Low Light
              - condition: and
                conditions:
                  - condition: state
                    entity_id: light.guest_bedroom_bedside_lamp_left
                    state: "off"
                  - condition: state
                    entity_id: light.guest_bedroom_bedside_lamp_right
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.guest_bedroom_bedside_lamps_active
                    state: "on"
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.guest_bedroom_motion_occupancy
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.guest_bedroom_camera_cell_motion_detection
                    state: "on"
              - condition: state
                entity_id: binary_sensor.lights_out
                state: "off"
            sequence:
              - service: light.turn_on
                data:
                  color_temp: 500
                  brightness_pct: 5
                target:
                  entity_id:
                    - light.guest_bedroom_bedside_lamp_left
                    - light.guest_bedroom_bedside_lamp_right
          - conditions:
              - condition: trigger
                id:
                  - Good Light
            sequence:
             - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.guest_bedroom_bedside_lamp_left
                    - light.guest_bedroom_bedside_lamp_right

###############################
#    Smart Button Upstairs 1  #
###############################

  - id: smart_button_upstairs_1_automations
    alias: Smart Button Upstairs 1 Automations
    description: ""
    initial_state: true
    mode: single
    trigger:
      - platform: state
        entity_id:
          - sensor.smart_button_upstairs_1_action
        id: Casper & Sky on
        to: single
      - platform: state
        entity_id:
          - sensor.smart_button_upstairs_1_action
        to: double
        id: Casper & Sky off
     - platform: state
        entity_id:
          - sensor.smart_button_upstairs_1_action
        attribute: action
        to: release 
        id: Night Lights
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: Casper & Sky on
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.casper_switch_0
              - service: media_player.turn_on
                data: {}
                target:
                  entity_id: media_player.sky_q_guest_bedroom_mini
              - if:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                then:
                  - service: script.status_annc
                    data:
                      where: Guest Bedroom
                      call_interruption: 1
                      call_media_system_on: 1
          - conditions:
              - condition: trigger
                id: Casper & Sky off
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.casper_switch_0
              - service: media_player.turn_off
                data: {}
                target:
                  entity_id: media_player.sky_q_guest_bedroom_mini
              - if:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                then:
                  - service: script.status_annc
                    data:
                      where: Guest Bedroom
                      call_interruption: 1
                      call_media_system_off: 1          
          - conditions:
              - condition: trigger
                id: Night Lights
            sequence:
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: input_boolean.guest_bedroom_bedside_lamps_active
              - service: light.turn_on
                data:
                  rgb_color:
                  - 255
                  - 244
                  - 4
                  brightness: 5
                target:
                  entity_id: 
                    - light.guest_bedroom_bedside_lamp_right
                    - light.guest_bedroom_bedside_lamp_left
                  
                


###########################
#        Scripts          #
###########################

