###############################################################################
#   @author         :   Dave Forrester                                        #
#   @date           :   23/08/2023                                            #
#   @package        :   Holiday House Mode                                    #
#   @description    :   Lights and TVs                                        #
#                                                                             #
#   @modified by    :                                                         #  
#   @date           :                                                         # 
###############################################################################

###############################################################################
#   Randomised Lights                                                         #
###############################################################################

automation:
  - alias: Run Holiday Lights
    description: ""
    trigger:
      - platform: sun
        event: sunset
        id: sundown
      - platform: sun
        event: sunrise
        id: sunup
      - platform: state
        entity_id: input_boolean.holiday_mode
        id: cancel
        from: "off"
        to: "on"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: sundown
              - condition: state
                entity_id: input_boolean.holiday_mode
                state: "on"
            sequence:
              - service: script.turn_on
                target:
                  entity_id: script.randomised_holiday_lighting
                data: {}
          - conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: sunup
                  - condition: trigger
                    id: cancel
            sequence:
              - service: script.turn_off
                target:
                  entity_id: script.randomised_holiday_lighting
                data: {}
        default: []
    mode: single
  
  ########################################################################
  #  TVs on and off plus dimming of lights at night                      #
  ########################################################################
  
  - alias: Holiday House Mode
    description: ""
    trigger:
      - platform: time
        at: "07:30:00"
        id: Morning
      - platform: time
        at: "12:00:00"
        id: Lunchtime
      - platform: time
        at: "17:35:00"
        id: Dinnertime
      - platform: time
        at: "20:45:00"
        id: Evening
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    action:
      - service: script.house_in_holiday_mode
        data: {}
    mode: single


script:
