###############################################################################
# Countdown Sensor using WolfRam Alpha Natural language queries
################################################################################
sensor:
  - platform: rest
    name: Halloween Countdown
    resource: !secret wolframalpha_halloween_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Christmas Countdown
    resource: !secret wolframalpha_christmas_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Easter Countdown
    resource: !secret wolframalpha_easter_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Mothers Day Countdown
    resource: !secret wolframalpha_mothers_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Fathers Day Countdown
    resource: !secret wolframalpha_fathers_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: St Andrews Day Countdown
    resource: !secret wolframalpha_andrew_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: St Georges Day Countdown
    resource: !secret wolframalpha_george_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: St Davids Day Countdown
    resource: !secret wolframalpha_david_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

################################################
#   These are events rather than holidays      #
################################################

  - platform: rest
    name: Leonids Meteor Shower Countdown
    resource: !secret wolframalpha_leonids_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Gemenids Meteor Shower Countdown
    resource: !secret wolframalpha_gemenids_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Perseids Meteor Shower Countdown
    resource: !secret wolframalpha_perseids_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

  - platform: rest
    name: Quadrantids Meteor Shower Countdown
    resource: !secret wolframalpha_quadrantids_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200

 - platform: rest
    name: Halley's Comet Countdown
    resource: !secret wolframalpha_halley_api
    value_template: "{{ (value|replace(' days', '')) | int }}"
    unit_of_measurement: Days
    scan_interval: 43200 

  

 # - platform: rest
 #   name: Thanksgiving Day Countdown
 #   resource: !secret wolframalpha_thanksgiving_api
 #   value_template: "{{ (value|replace(' days', '')) | int }}"
 #   unit_of_measurement: Days
 #   scan_interval: 43200
