###############################################################################
#   @author         :   Rueben Gow (@reuben.guru)                             #
#   @date           :   March 2023                                            #
#   @package        :   Home Battery Automations                              #
#   @description    :   Controls home battery charge, discharge and output    # 
#                       limit during EV charging                              #
#                                                                             #
#   @modified by    :   Dave Forrester(@Daverover66)                          #
#   @date           :   01/02/2024                                            #
#   @modification   :                                                         #
############################################################################### 

########################
#       Helpers        #
########################

########################
#       Datetime       #
########################
input_datetime:
  get_desired_charge_notification_at:
    name: Send Desired Charge Notification at
    has_date: false
    has_time: true 

  get_desired_discharge_notification_at:
    name: Send Desired Discharge Notification at
    has_date: false
    has_time: true

  start_battery_discharge:
    name: Start Battery Discharge at
    has_date: false
    has_time: true
    icon: mdi:battery-clock

   end_battery_discharge:
    name: End Battery Discharge at
    has_date: false
    has_time: true
    icon: mdi:battery-clock-outline

  start_charge_from_clipped_solar:
    name: Start Charge from Clipped Solar
    has_date: false
    has_time: true
    icon: mdi:solar-power-variant

  start_battery_output_limit:
    name: Start Battery Output Limit Slot 1 at
    has_date: false
    has_time: true
    icon: mdi:battery-minus-variant

  end_battery_output_limit:
    name: End Battery Output Limit Slot 1 at
    has_date: false
    has_time: true
    icon: mdi:battery-plus-variant

  start_battery_output_limit_slot_2:
    name: Start Battery Output Limit Slot 2 at
    has_date: false
    has_time: true
    icon: mdi:battery-minus-variant

  end_battery_output_limit_slot_2:
    name: End Battery Output Limit Slot 2 at
    has_date: false
    has_time: true
    icon: mdi:battery-plus-variant

  start_battery_output_limit_slot_3:
    name: Start Battery Output Limit Slot 3 at
    has_date: false
    has_time: true
    icon: mdi:battery-minus-variant

  end_battery_output_limit_slot_3:
    name: End Battery Output Limit Slot 3 at
    has_date: false
    has_time: true
    icon: mdi:battery-plus-variant

  start_battery_output_limit_slot_4:
    name: Start Battery Output Limit Slot 4 at
    has_date: false
    has_time: true
    icon: mdi:battery-minus-variant

  end_battery_output_limit_slot_4:
    name: End Battery Output Limit Slot 4 at
    has_date: false
    has_time: true
    icon: mdi:battery-plus-variant

    
########################
#       Toggle         #
########################
input_boolean:
  grid_charge_home_battery:
    name: Grid Charge Home Battery

  allow_battery_grid_discharge:
    name: Allow Battery Grid Discharge

  allow_battery_output_limit:
    name: Allow Battery Output Limit
    icon: mdi:battery-arrow-down

  battery_output_limit_slot_1:
    name: Battery Output Limit Slot 1

  battery_output_limit_slot_2:
    name: Battery Output Limit Slot 2

    battery_output_limit_slot_3:
    name: Battery Output Limit Slot 3

  battery_output_limit_slot_4:
    name: Battery Output Limit Slot 4

  home_battery_grid_charging:
    name: Home Battery Grid Charging
    icon: mdi:battery-charging

  desired_storage_cmd_mode_correct:
    name: Desired Storage Cmd Mode Correct
    icon: mdi:battery-check

  desired_storage_default_mode_correct:
    name: Desired Storage Default Mode Correct
    icon: mdi:battery-check

  desired_storage_control_mode_correct:
    name: Desired Storage Control Mode Correct
    icon: mdi:battery-check

########################
#       Number         #
########################
input_number:
  default_battery_percentage:
    name: Default Battery Charge %
    min: 0
    max: 100
    initial: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:battery-lock

  desired_battery_percentage:
    name: Desired Battery Charge %
    min: 0
    max: 100
    initial: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:battery-plus

  default_battery_discharge_percentage:
    name: Default Battery Discharge %
    min: 0
    max: 100
    initial: 100
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:battery-minus

  desired_battery_discharge_percentage:
    name: Desired Battery Discharge %
    min: 0
    max: 100
    initial: 50
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:battery-minus  

  solar_production_threshold_for_grid_charging_battery:
    name: Solar Production Threshold For Grid Charging Battery
    min: 0
    max: 40
    initial: 35
    step: 1
    mode: box
    unit_of_measurement: "kWh"
    icon: mdi:solar-power-variant

  storage_command_timeout_period_for_clipped_solar:
    name: Storage Command Timeout Period for Clipped Solar
    min: 0
    max: 86400
    initial: 30600
    step: 1
    mode: box

  storage_command_timeout_for_discharge_to_grid:
    name: Storage Command Timeout Period for Discharge to Grid
    min: 0
    max: 86400
    initial: 10800
    step: 1
    mode: box 

  storage_command_timeout_default_period:
    name: Storage Command Timeout Default Period
    min: 0
    max: 86400
    initial: 3600
    step: 1
    mode: box   

  default_battery_output_limit:
    name: Default Battery Output Limit
    min: 0
    max: 7000
    initial: 7000
    step: 100
    mode: box   
    unit_of_measurement: "W"
    icon: mdi:battery_lock

  battery_output_limit:
    name: Desired Battery Output Limit Day Discharge
    min: 0
    max: 7000
    initial: 7000
    step: 100
    mode: box   
    unit_of_measurement: "W"
    icon: mdi:battery-lock

  desired_battery_output_limit_for_overnight_ev_charging:
    name: Desired Battery Output Limit for Overnight EV charging
    min: 0
    max: 300
    initial: 5
    step: 1
    mode: box   
    unit_of_measurement: "W"
    icon: mdi:battery-lock
    

########################
#       Select         #
########################

input_select:
  desired_battery_storage_command_mode:
    name: Desired Battery Storage Command Mode
    icon: mdi:home-battery
    options:
      - Solar Power Only (Off)
      - Charge from Clipped Solar Power
      - Charge from Solar Power
      - Charge from Solar Power and Grid
      - Discharge to Maximize Export
      - Discharge to Minimize Import
      - Maximize Self Consumption
    initial: Maximize Self Consumption

  desired_battery_storage_control_mode:
    name: Desired Battery Storage Control Mode
    icon: mdi:battery-lock
    options:
      - Disabled
      - Maximize Self Consumption
      - Time of Use
      - Backup Only
      - Remote Control
    initial: Remote Control

  desired_battery_storage_default_mode:
    name: Desired Battery Storage Default Mode
    icon: mdi:battery-lock
    options:
      - Solar Power Only (Off)
      - Charge from Clipped Solar Power
      - Charge from Solar Power
      - Charge from Solar Power and Grid
      - Discharge to Maximize Export
      - Discharge to Minimize Import
      - Maximize Self Consumption
    initial: Maximize Self Consumption
  

########################
#      Automations     #
########################  
automation:

##########################################
#       Battery Settings Confirm         #
##########################################

  - id: battery_settings_confirm 
    alias: Battery Settings Confirm
    description: checks to see if battery settings are correct and sets an input boolean toggle
    trigger:
      - platform: state
        entity_id:
          - select.solaredge_i1_storage_default_mode
        from: Maximize Self Consumption
        id: Storage Default Mode Wrong
      - platform: state
        entity_id:
          - select.solaredge_i1_storage_default_mode
        id: Storage Default Mode Correct
        to: Maximize Self Consumption
      - platform: state
        entity_id:
          - select.solaredge_i1_storage_command_mode
        from: Maximize Self Consumption
        id: Storage Cmd Mode Wrong
      - platform: state
        entity_id:
          - select.solaredge_i1_storage_command_mode
        id: Storage Cmd Mode Correct
        to: Maximize Self Consumption
      - platform: state
        entity_id:
          - select.solaredge_i1_storage_control_mode
        from: Remote Control
        id: Storage Control Mode Wrong
      - platform: state
        entity_id:
          - select.solaredge_i1_storage_control_mode
        id: Storage Control Mode Correct
        to: Remote Control
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: Storage Default Mode Wrong
              - condition: state
                entity_id: input_boolean.desired_storage_default_mode_correct
                state: "on"
            sequence:
              - service: input_boolean.toggle
                data: {}
                target:
                  entity_id: input_boolean.desired_storage_default_mode_correct
          - conditions:
              - condition: trigger
                id: Storage Default Mode Correct
              - condition: state
                entity_id: input_boolean.desired_storage_default_mode_correct
                state: "off"
            sequence:
              - service: input_boolean.toggle
                data: {}
                target:
                  entity_id: input_boolean.desired_storage_default_mode_correct
          - conditions:
              - condition: trigger
                id: Storage Cmd Mode Wrong
              - condition: state
                entity_id: input_boolean.desired_storage_cmd_mode_correct
                state: "on"
            sequence:
              - service: input_boolean.toggle
                data: {}
                target:
                  entity_id: input_boolean.desired_storage_cmd_mode_correct
          - conditions:
              - condition: trigger
                id: Storage Cmd Mode Correct
              - condition: state
                entity_id: input_boolean.desired_storage_cmd_mode_correct
                state: "off"
            sequence:
              - service: input_boolean.toggle
                data: {}
                target:
                  entity_id: input_boolean.desired_storage_cmd_mode_correct
          - conditions:
              - condition: trigger
                id: Storage Control Mode Wrong
              - condition: state
                entity_id: input_boolean.desired_storage_control_mode_correct
                state: "on"
            sequence:
              - service: input_boolean.toggle
                data: {}
                target:
                  entity_id: input_boolean.desired_storage_control_mode_correct
          - conditions:
              - condition: trigger
                id: Storage Control Mode Correct
              - condition: state
                entity_id: input_boolean.desired_storage_control_mode_correct
                state: "off"
            sequence:
              - service: input_boolean.toggle
                data: {}
                target:
                  entity_id: input_boolean.desired_storage_control_mode_correct
    mode: restart

########################################################
#       Grid Charge Battery During Agile Plunge        #
########################################################

  - id: grid_charge_battery_during_plunge_pricing   
    alias: "Grid Charge Battery during Plunge Pricing "
    description: ""
    trigger:
      - platform: state
        entity_id: input_boolean.plunge_pricing
        from: "off"
        to: "on"
        id: Start Charge
      - platform: state
        entity_id: input_boolean.plunge_pricing
        from: "on"
        to: "off"
        id: Stop Charge
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Start Charge
              - condition: state
                entity_id: input_boolean.home_battery_grid_charging
                state: "off"
            sequence:
              - service: notify.persistent_notification
                data:
                  message: The home battery is charging
                  title: Price Plunge Started
              - service: script.grid_charge_battery
                data: {}
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.home_battery_grid_charging
                data: {}
          - conditions:
              - condition: trigger
                id:
                  - Stop Charge
              - condition: state
                entity_id: input_boolean.home_battery_grid_charging
                state: "on"
            sequence:
              - service: notify.persistent_notification
                data:
                  message: The home battery has stopped charging
                  title: Price Plunge Over
    mode: single

##########################################
#           Home Battery Watch           #
##########################################

 -  id: home_battery_watch
    alias: Home Battery Watch
    description: Notify me if there is a problem with the home battery
    trigger:
      - platform: state
        entity_id:
          - sensor.solaredge_b1_status
        to: B_STATUS_IDLE
        id: Home Battery Idle
        for:
          hours: 0
          minutes: 2
          seconds: 0
      - platform: state
        entity_id:
          - sensor.solaredge_b1_status
        to: unavailable
        for:
          hours: 0
          minutes: 2
          seconds: 0
        id: Home Battery Unavailable
      - platform: state
        entity_id:
          - sensor.solaredge_b1_status
        to: unknown
        for:
          hours: 0
          minutes: 2
          seconds: 0
        id: Home Battery Unknown
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: Home Battery Idle
              - condition: sun
                after: sunset
            sequence:
              - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
                data:
                  message: The Home Battery is idle
                  title: HOME BATTERY
                alias: Send a notification based on an input text helper
          - conditions:
              - condition: or
                conditions:
                  - condition: trigger
                    id: Home Battery Unavailable
                  - condition: trigger
                    id: Home Battery Unknown
            sequence:
              - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
                data:
                  message: There is a problem with the Home Battery
                  title: HOME BATTERY
                alias: Send a notification based on an input text helper
              - service: notify.alexa_media_kitchen_echo_show
                data:
                  message: There is a problem with the home battery
                  title: HOME BATTERY
                  data:
                    type: announce
                    method: all
    mode: single


########################
#       Scripts        #
########################
