###############################################################################
#   @author         :   Dave Forrester (@Daverover66)
#   @date           :   08/09/2023
#   @package        :   Kitchen
#   @description    :   All Kitchen config
#
#   @modified by    :   Dave Forrester
#   @date           :   14/09/2023
###############################################################################

###########################
#       Helpers           #
###########################


###########################
#     Automations         #
###########################
automation:
###########################
       Lighting           
###########################

  - id: kitchen_lights_with_presence
    alias: Kitchen Lights with Presence
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_presence_sensor_presence_sensor_1
        from: "off"           
        to: "on"
        id: Lights On
      - platform: state
        entity_id:
          - binary_sensor.kitchen_presence_sensor_presence_sensor_1
        from: "on"
        to: "off"
        id: Lights Off
      - platform: numeric_state
        entity_id: sensor.kitchen_presence_sensor_light_sensor_light_level
        below: input_number.low_light_threshold
        id: Low Light
      - platform: numeric_state
        entity_id: sensor.kitchen_presence_sensor_light_sensor_light_level
        above: input_number.upper_light_threshold_level
        id: Good Light
      - platform: state
        entity_id:
          - binary_sensor.lunchtime
        from: "off"
        to: "on"
        id: Lunchtime starts
      - platform: state
        entity_id:
          - binary_sensor.lunchtime
        id: lunchtime ends
      - platform: state
        entity_id:
          - binary_sensor.dinner_time
        from: "off"
        to: "on"
        id: Dinner Time Starts
      - platform: state
        entity_id:
          - binary_sensor.dinner_time
        from: "on"
        to: "off"
        id: Dinner Time Ends
    condition:
      - condition: state
        entity_id: binary_sensor.lights_out
        state: "off"
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Lights On
              - condition: state
                entity_id: binary_sensor.morning
                state: "on"
              - condition: numeric_state
                entity_id: sensor.kitchen_presence_sensor_light_sensor_light_level
                below: input_number.low_light_threshold
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
          - conditions:
              - condition: trigger
                id:
                  - Lights On
              - condition: state
                entity_id: binary_sensor.lunchtime
                   state: "on"
                 - condition: numeric_state
                   entity_id: sensor.kitchen_presence_sensor_light_sensor_light_level
                   below: input_number.low_light_threshold
               sequence:
                 - service: scene.turn_on
                   data: {}
                   target:
                     entity_id: scene.kitchen_lights_mealtimes
          - conditions:
              - condition: trigger
                id:
                  - Lights On
              - condition: state
                entity_id: binary_sensor.afternoon
                state: "on"
              - condition: numeric_state
                entity_id: sensor.kitchen_presence_sensor_light_sensor_light_level
                below: input_number.low_light_threshold
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
          - conditions:
              - condition: trigger
                id:
                  - Lights On
              - condition: state
                entity_id: binary_sensor.dinner_time
                state: "on"
              - condition: numeric_state
                entity_id: sensor.kitchen_presence_sensor_light_sensor_light_level
                below: input_number.low_light_threshold
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_mealtimes
          - conditions:
              - condition: trigger
                id:
                  - Lights On
              - condition: state
                entity_id: binary_sensor.evening
                state: "on"
              - condition: numeric_state
                entity_id: sensor.kitchen_presence_sensor_light_sensor_light_level
                below: input_number.low_light_threshold
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
          - conditions:
              - condition: trigger
                id:
                  - Lights Off
              - condition: state
                entity_id: light.kitchen_lights_2
                state: "on"
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.kitchen_lights_2
              - if:
                  - condition: state
                    entity_id: input_boolean.garage_dehumidifier_full
                    state: "on"
                then:
                  - service: scene.turn_on
                    data: {}
                    target:
                      entity_id: scene.kitchen_light_indicator_garage_dehumidifier
              - if:
                  - condition: state
                    entity_id: input_boolean.washing_machine_on_off
                    state: "on"
                then:
                  - service: scene.turn_on
                    data: {}
                    target:
                      entity_id:
                        - scene.kitchen_light_indicator_washing_machine_finished
          - conditions:
              - condition: trigger
                id:
                  - Low Light
              - condition: state
                entity_id: binary_sensor.kitchen_presence_sensor_presence_sensor_1
                state: "on"
              - condition: state
                entity_id: binary_sensor.morning
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
          - conditions:
              - condition: trigger
                id:
                  - Low Light
              - condition: state
                entity_id: binary_sensor.kitchen_presence_sensor_presence_sensor_1
                state: "on"
              - condition: state
                entity_id: binary_sensor.lunchtime
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_mealtimes
          - conditions:
              - condition: trigger
                id:
                  - Low Light
              - condition: state
                entity_id: binary_sensor.kitchen_presence_sensor_presence_sensor_1
                state: "on"
              - condition: state
                entity_id: binary_sensor.afternoon
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
          - conditions:
              - condition: trigger
                id:
                  - Low Light
              - condition: state
                entity_id: binary_sensor.kitchen_presence_sensor_presence_sensor_1
                state: "on"
              - condition: state
                entity_id: binary_sensor.dinner_time
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_mealtimes
          - conditions:
              - condition: trigger
                id:
                  - Low Light
              - condition: state
                entity_id: binary_sensor.kitchen_presence_sensor_presence_sensor_1
                state: "on"
              - condition: state
                entity_id: binary_sensor.evening
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
          - conditions:
              - condition: trigger
                id:
                  - Good Light
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.kitchen_lights_2
              - if:
                  - condition: state
                    entity_id: input_boolean.garage_dehumidifier_full
                    state: "on"
                then:
                  - service: scene.turn_on
                    data: {}
                    target:
                      entity_id: scene.kitchen_light_indicator_garage_dehumidifier
              - if:
                  - condition: state
                    entity_id: input_boolean.washing_machine_on_off
                    state: "on"
                then:
                  - service: scene.turn_on
                    data: {}
                    target:
                      entity_id:
                        - scene.kitchen_light_indicator_washing_machine_finished
          - conditions:
              - condition: trigger
                id:
                  - Lunchtime starts
              - condition: state
                entity_id: light.kitchen_lights_2
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_mealtimes
          - conditions:
              - condition: trigger
                id:
                  - lunchtime ends
              - condition: state
                entity_id: light.kitchen_lights_2
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
          - conditions:
              - condition: trigger
                id:
                  - Dinner Time Starts
              - condition: state
                entity_id: light.kitchen_lights_2
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_mealtimes
          - conditions:
              - condition: trigger
                id:
                  - Dinner Time Ends
              - condition: state
                entity_id: light.kitchen_lights_2
                state: "on"
            sequence:
              - service: scene.turn_on
                data: {}
                target:
                  entity_id: scene.kitchen_lights_normal
    mode: restart

########################
     Magic Cube
########################

  - id: magic_cube_stuff
    alias: Magic Cube Stuff
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - sensor.magic_cube_side
        to: "1"
        id: Side 1
      - platform: state
        entity_id:
          - sensor.magic_cube_side
        to: "2"
        id: Side 2
      - platform: state
        entity_id:
          - sensor.magic_cube_side
        to: "3"
        id: Side 3
      - platform: state
        entity_id:
          - sensor.magic_cube_side
        to: "4"
        id: Side 4
      - platform: state
        entity_id:
          - sensor.magic_cube_side
        to: "5"
        id: Side 5
      - platform: state
        entity_id:
          - sensor.magic_cube_side
        to: "6"
        id: Side 6
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Side 1
             - condition: state
                entity_id: binary_sensor.quiet_time
                state: "off"
            sequence:
              - service: script.status_annc
                data:
                  where: Kitchen
                  call_mc_side_not_set: 1
          - conditions:
              - condition: trigger
                id:
                  - Side 2
              - condition: state
                entity_id: binary_sensor.quiet_time
                state: "off"
            sequence:
              - service: script.status_annc
                data:
                  where: Kitchen
                  call_mc_side_not_set: 1
          - conditions:
              - condition: trigger
                id:
                  - Side 3
                  - Side 4
             - condition: state
                entity_id: binary_sensor.quiet_time
                state: "off" 
            sequence:
              - service: script.status_annc
                data:
                  where: Kitchen
                  call_coffee_timer: 1
              - delay:
                  hours: 0
                  minutes: 4
                  seconds: 0
                  milliseconds: 0
                alias: Wait 4 minutes
              - service: script.status_annc
                data:              
                  where: "{{states('sensor.room_audio')}}"
                  call_coffee_ready: 1
          - conditions:
              - condition: trigger
                id: Side 6
              - condition: state
                entity_id: binary_sensor.quiet_time
                state: "off"
            sequence:
              - service: script.status_annc
                data:
                  where: "{{states('sensor.room_audio')}}"
                  call_dinner_weekday: 1
          - conditions:
              - condition: trigger
                id: Side 5
              - condition: state
                entity_id: binary_sensor.quiet_time
                state: "off"
            sequence:
              - service: script.status_annc
                data:
                  where: "{{states('sensor.room_audio')}}"
                  call_dinner_sunday: 1

###############################
   Smart Button Downstairs 2
###############################

  - id: smart_button_downstairs_2
    alias: Smart Button Downstairs 2 Automations
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - sensor.smart_button_downstairs_2_action
        to: single
        id: Ingrid & Sky On
      - platform: state
        entity_id:
          - sensor.smart_button_downstairs_2_action
        to: double
        id: Ingrid & Sky Off
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Ingrid & Sky On
              - condition: state
                entity_id: switch.ingrid_socket_1
                state: "off"
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.ingrid_socket_1
              - service: media_player.turn_on
                data: {}
                target:
                  device_id: 2285e887e55f34f8b3cfd7d7e8e58f6a
              - if:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                then:
                  - service: script.status_annc
                    data:
                      where: Kitchen
                      call_media_system_on: 1
          - conditions:
              - condition: trigger
                id:
                  - Ingrid & Sky Off
              - condition: state
                entity_id: switch.ingrid_socket_1
                state: "on"
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.ingrid_socket_1
              - service: media_player.turn_off
                data: {}
                target:
                  device_id: 2285e887e55f34f8b3cfd7d7e8e58f6a
              - if:
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                then:
                  - service: script.status_annc
                    data:
                      where: Kitchen
                      call_media_system_off: 1



###########################
#        Scripts          #
###########################
