###############################################################################
#   @author         :   Dave Forrester (@Daverover66)
#   @date           :   08/09/2023
#   @package        :   Living Room
#   @description    :   All Living Room config
#
#   @modified by    :   Dave Forrester
#   @date           :   13/08/2024
###############################################################################

###########################
#     Helpers             #
###########################
input_number:
  upper_light_threshold_level:
    name: Upper Light Threshold Level
    initial: 90
    icon: mdi:brightness-4
    min: 50
    max: 150
    step: 1
    mode: box 
  low_light_threshold:
    name: Low Light Threshold
    initial: 50
    icon: mdi:brightness-3
    min: 5
    max: 70
    step: 1
    mode: box 
###########################
#     Sensors             #
###########################


###########################
#     Automations         #
###########################

###########################
#         Lights          #
###########################

automation:
  - id: living_room_lights
    alias: Living Room Lights
    initial_state: true
    mode: restart
    trigger:
      - platform: state 
        entity_id: light.living_room_lights
        from: "off"
        to: "on"
        id: Ceiling Light On 
      - platform: state 
        entity_id: light.living_room_lights
        from: "on"
        to: "off"
        id: Ceiling Light Off 
      - platform: state
        entity_id:
          - binary_sensor.living_room_fp2_presence_sensor_1
        from: "off"
        to: "on"
        id: Light On With Presence
      - platform: state
        entity_id:
          - binary_sensor.living_room_fp2_presence_sensor_1
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
        id: Light Off With No Presence
      - platform: numeric_state 
        entity_id: sensor.living_room_fp2_light_sensor_light_level
        below: input_number.low_light_threshold
        for:
          seconds: 20
        id: Low Light 
      - platform: numeric_state
        entity_id: sensor.living_room_fp2_light_sensor_light_level
        above: input_number.upper_light_threshold_level 
        for:
          seconds: 20
        id: Good Light 
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger 
                id:
                  - Ceiling Light On 
            sequence: 
              - service: light.turn_off 
                data: {}
                target: 
                  entity_id: 
                    - light.corner_lamp_2
                    - light.dreamview_g1_pro_2
          - conditions:
              - condition: trigger 
                id:
                  - Ceiling Light Off 
              - condition: numeric_state 
                entity_id: sensor.living_room_fp2_light_sensor_light_level 
                below: input_number.low_light_threshold
            sequence: 
              - service: light.turn_on  
                data: {}
                target: 
                  entity_id: 
                    - light.corner_lamp_2
              - if:
                  - condition: state
                    entity_id: switch.living_room_tv 
                    state: "on"
                then:
                  - service: light.turn_on
                    data: {}
                    target:
                      entity_id: light.dreamview_g1_pro_2
          - conditions:
              - condition: trigger
                id:
                  - Light On With Presence
                alias: Light on with presence
              - condition: numeric_state
                entity_id: sensor.living_room_fp2_light_sensor_light_level
                below: input_number.low_light_threshold
            sequence:
              - service: light.turn_on
                data: {}
                target: 
                  entity_id: 
                    - light.corner_lamp_2
              - service: light.turn_on
                data: {}
                target: 
                  entity_id: 
                    - light.standard_lamp
          - conditions:
              - condition: trigger
                id:
                  - Light Off With No Presence
                alias: Light off with no presence
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.corner_lamp_2
              - service: light.turn_off 
                data: {}
                target: 
                  entity_id: 
                    - light.standard_lamp
          - conditions:
              - condition: trigger
                id:
                  - Low Light 
                alias: Light on when Low Light and Presence 
              - condition: state
                entity_id: binary_sensor.living_room_fp2_presence_sensor_1
                state: "on"
            sequence:
              - service: light.turn_on
                data: {}
                target: 
                  entity_id: 
                    - light.corner_lamp_2
              - service: light.turn_on
                data: {}
                target: 
                  entity_id: 
                    - light.standard_lamp
          - conditions:
              - condition: trigger
                id:
                  - Good Light 
                alias: Light off with Good Light 
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.corner_lamp_2
              - service: light.turn_off 
                data: {}
                target: 
                  entity_id: 
                    - light.standard_lamp

#########################################
#              Smart Button             #
#               TV and Sky              #
#########################################

  - id: smart_button_downstairs_1
    alias: Smart Button Downstairs 1 Automations
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.smart_button_downstairs_1_action
        to: release
        id: Good Night
      - platform: state
        entity_id:
          - sensor.smart_button_downstairs_1_action
        to: single
        id: TV & Sky on
      - platform: state
        entity_id:
          - sensor.smart_button_downstairs_1_action
        to: double
        id: TV & Sky off
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Good Night
              - condition: state
                entity_id: binary_sensor.overnight
                state: "on"
            sequence:
              - service: script.goodnight
                data: {}
          - conditions:
              - condition: trigger
                id:
                  - TV & Sky on
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.living_room_tv
              - service: media_player.turn_on
                data: {}
                target:
                  entity_id: media_player.sky_q_main
              - if:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                then:
                  - service: script.status_annc
                    data:
                      where: Living Room
                      call_interruption: 1
                      call_media_system_on: 1
          - conditions:
              - condition: trigger
                id: TV & Sky off
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.living_room_tv
              - service: media_player.turn_off
                data: {}
                target:
                  entity_id: media_player.sky_q_main
              - if:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                then:
                  - service: script.status_annc
                    data:
                      where: Living Room
                      call_interruption: 1
                      call_media_system_off: 1


  # - id: smart_button_downstairs_1
  #   alias: Smart Button Downstairs 1 Automations
  #   initial_state: true
  #   mode: restart
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - sensor.smart_button_downstairs_1_action
  #       attribute: action
  #       to: release
  #       id: Good Night
  #     - platform: state
  #       entity_id:
  #         - sensor.smart_button_downstairs_1_action
  #       to: single
  #       id: TV & Sky toggle
  #   condition: []
  #   action:
  #     - choose:
  #         - conditions:
  #             - condition: trigger
  #               id:
  #                 - Good Night
  #           sequence:
  #             - service: script.goodnight
  #               data: {} 
  #         - conditions:
  #             - condition: trigger
  #               id:
  #                 - TV & Sky toggle 
  #           sequence:
  #             - service: media_player.toggle
  #               data: {}
  #               target:
  #                 entity_id: media_player.sky_q_main


#####################################
#    TV and Sky Toggle on and off   #
#####################################

  # - id: living_room_tv_toggle_on_and_off 
  #   alias: Living Room TV Toggle On and Off 
  #   description: ""
  #   initial_state: true
  #   mode: single
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - media_player.sky_q_main
  #       id: Sky toggle on 
  #       from: "off"
  #       to: playing 
  #     - platform: state
  #       entity_id:
  #         - media_player.sky_q_main
  #       id: Sky toggle off 
  #       from: 
  #         - playing 
  #         - paused   
  #       to: "off" 
  #   condition: []
  #   action:
  #     - choose:
  #         - conditions:
  #             - condition: trigger
  #               id: Sky toggle on 
  #           sequence:
  #             - service: script.living_room_tv_toggle
  #               data: {} 
  #         - conditions:
  #             - condition: trigger
  #               id: Sky toggle off  
  #           sequence:
  #             - service: script.living_room_tv_toggle
  #               data: {} 

###########################
#     Scripts             #
###########################

script: 
  ###########################
  #   Toggle TV on and off  # 
  ###########################
  living_room_tv_toggle:
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.living_room_tv
                state: "off"
            sequence:
              - service: switch.turn_on
                target:
                  entity_id: switch.living_room_tv 
                data: {}
              - condition: and
                conditions:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
              - service: script.status_annc
                data:
                  where: living_room 
                  call_interruption: 1
                  call_media_system_on: 1
        default:
          - service: switch.turn_off
            target:
              entity_id: switch.living_room_tv 
            data: {}
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.quiet_time
                state: "off"
              - condition: state
                entity_id: input_boolean.audible_notifications
                state: "on"
          - service: script.status_annc
            data:
              where: living_room 
              call_interruption: 1
              call_media_system_off: 1
    mode: single

  ###################
  #    Goodnight    #
  ###################
    
  goodnight:
    sequence:
      - condition: state
        entity_id: binary_sensor.overnight
        state: "on"
      - service: script.night_security_check
        data: {}
      - service: media_player.turn_off
        data: {}
        target:
          entity_id: media_player.sky_q_main
      - service: switch.turn_off 
        target:
          entity_id: switch.living_room_tv 
        data: {}
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.seans_morning_briefing_played
        data: {}
      - service: switch.turn_off
        target:
          entity_id: switch.under_shelf_lights_local
        data: {}
      - service: light.turn_off
        target:
          entity_id:
            - light.standard_lamp
            - light.corner_lamp_2
        data: {}
      - service: script.bed_lamps_dim_at_bedtime
        data: {}
    mode: single
