###############################################################################
#   @author         :   Dave Forrester (@Daverover66)
#   @date           :   08/09/2023
#   @package        :   Living Room
#   @description    :   All Living Room config
#
#   @modified by    :   
#   @date           :   
###############################################################################

###########################
#     Helpers             #
###########################

###########################################
#     Input Number for threshold levels   #
###########################################

input_number:
  upper_light_threshold_level:
    name: Upper Light Threshold Level
    initial: null
    editable: true
    icon: mdi:brightness-4
    min: 60
    max: 100
    step: 1
    mode: slider
 low_light_threshold:
   name: Low Light Threshold
   initial: null
   editable: true
   icon: mdi:brightness-3
   min: 0
   max: 25
   step: 1
   mode: slider
    
###########################
#     Sensors             #
###########################


###########################
#     Automations         #
###########################

###########################
#         Lights          #
###########################

automation:
  - id: living_room_lights
    alias: Living Room Lights
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.living_room_fp2_presence_sensor_1
        from: "off"
        to: "on"
        id: Light On With Presence
      - platform: state
        entity_id:
          - binary_sensor.living_room_fp2_presence_sensor_1
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
        id: Light Off With No Presence
      - platform: numeric_state
        entity_id: sensor.living_room_fp2_light_sensor_light_level
        below: input_number.low_light_threshold
        id: Light On With Low Light
      - platform: numeric_state
        entity_id: sensor.living_room_fp2_light_sensor_light_level
        above: input_number.upper_light_threshold_level
        id: Light Off With Good Light
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Light On With Presence
                alias: Light on with presence
              - condition: numeric_state
                entity_id: sensor.living_room_fp2_light_sensor_light_level
                below: input_number.low_light_threshold
            sequence:
              - service: light.turn_on
                data:
                  color_temp: 500
                  brightness_pct: 30
                target:
                  entity_id:
                    - light.corner_lamp
                    - light.standard_lamp
          - conditions:
              - condition: trigger
                id:
                  - Light Off With No Presence
                alias: Light off with no presence
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.corner_lamp
                    - light.standard_lamp
          - conditions:
              - condition: trigger
                id:
                  - Light On With Low Light
                alias: Light on with low light and presence
              - condition: state
                entity_id: input_boolean.living_room_occupied
                state: "on"
            sequence:
              - service: light.turn_on
                data:
                  color_temp: 500
                  brightness_pct: 30
                target:
                  entity_id:
                    - light.corner_lamp
                    - light.standard_lamp
          - conditions:
              - condition: trigger
                id:
                  - Light Off With Good Light
                alias: Light off with good light
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.corner_lamp
                    - light.standard_lamp

#########################################
#              Smart Button             #
#               TV and Sky              #
#########################################

  - id: smart_button_downstairs_1
    alias: Smart Button Downstairs 1 Automations
    mode: restart
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.smart_button_downstairs_1_action
        attribute: action
        to: release
        id: Good Night
      - platform: state
        entity_id:
          - sensor.smart_button_downstairs_1_action
        to: single
        id: TV & Sky on
      - platform: state
        entity_id:
          - sensor.smart_button_downstairs_1_action
        to: double
        id: TV & Sky off
      - platform: numeric_state
        entity_id: sensor.living_room_fp2_light_sensor_light_level
        below: 30
        alias: Low Light
        id: Low Light
      - platform: numeric_state
        entity_id: sensor.living_room_fp2_light_sensor_light_level
        above: 50
        id: High Light
        alias: High Light
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Good Night
              - condition: state
                entity_id: binary_sensor.overnight
                state: "on"
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.living_room_tv
              - service: media_player.turn_off
                data: {}
                target:
                  device_id: 4aa503b5c01d5c68b0ad4341bdc9dd65
                enabled: true
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.dreamview_g1_pro
              - type: turn_off
                device_id: 23629338a1f8b2487860c2b962ce2a4b
                entity_id: switch.under_shelf_lights_local
                domain: switch
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.corner_lamp
                    - light.standard_lamp
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id:
                    - input_boolean.kids_bedtime_announcement_played
                    - input_boolean.school_pick_up_announcement_played
                    - input_boolean.school_morning_announcement_played
                    - input_boolean.morning_briefing_played
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.guest_bedroom_camera_privacy
              - service: switch.turn_on
                data: {}
                target:
                  entity_id:
                    - switch.jamie_s_room_cam_privacy
              - service: switch.turn_on
                data: {}
                target:
                  entity_id:
                    - switch.seans_room_camera_privacy
              - service: script.bed_lamps_dim_at_bedtime
                data: {}
          - conditions:
              - condition: trigger
                id:
                  - TV & Sky on
            sequence:
              - service: switch.turn_on
                data: {}
                target:
                  entity_id: switch.living_room_tv
              - service: media_player.turn_on
                data: {}
                target:
                  entity_id: media_player.sky_q_main
              - if:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                then:
                  - service: script.status_annc
                    data:
                      where: living_room
                      call_media_system_on: 1     
              - if:
                  - condition: numeric_state
                    entity_id: sensor.living_room_fp2_light_sensor_light_level
                    below: 50
                then:
                  - service: light.turn_on
                    data: {}
                    target:
                      entity_id: light.dreamview_g1_pro
          - conditions:
              - condition: trigger
                id: TV & Sky off
            sequence:
              - service: switch.turn_off
                data: {}
                target:
                  entity_id: switch.living_room_tv
              - service: media_player.turn_off
                data: {}
                target:
                  entity_id: media_player.sky_q_main
              - if:
                  - condition: state
                    entity_id: binary_sensor.quiet_time
                    state: "off"
                  - condition: state
                    entity_id: input_boolean.audible_notifications
                    state: "on"
                then:
                  - service: script.status_annc
                    data:
                      where: living_room
                      call_media_system_off: 1
              - if:
                  - condition: state
                    entity_id: light.dreamview_g1_pro
                    state: "on"
                then:
                  - service: light.turn_off
                    data: {}
                    target:
                      entity_id: light.dreamview_g1_pro
          - conditions:
              - condition: trigger
                id:
                  - TV & Sky on
              - condition: numeric_state
                entity_id: sensor.living_room_fp2_light_sensor_light_level
                below: 30
            sequence:
              - service: light.turn_on
                data: {}
                target:
                  entity_id: light.dreamview_g1_pro
          - conditions:
              - condition: trigger
                id:
                  - TV & Sky off
                  - High Light
              - condition: state
                entity_id: light.dreamview_g1_pro
                state: "on"
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.dreamview_g1_pro
          - conditions:
              - condition: trigger
                id:
                  - Low Light
            sequence:
              - if:
                  - condition: state
                    entity_id: switch.living_room_tv
                    state: "on"
                then:
                  - service: light.turn_on
                    data: {}
                    target:
                      entity_id: light.dreamview_g1_pro
    

###########################
#     Scripts             #
###########################
