###############################################################################
#   @author         :   Dave Forrester (@Daverover66)
#   @date           :   08/09/2023
#   @package        :   Main Bedroom
#   @description    :   All Main Bedroom config
#
#   @modified by    :   Dave Forrester
#   @date           :   21/09/2023
###############################################################################

###########################
#       Helpers           #
###########################

###########################
#       Timer             #
###########################

timer:
  en_suite_bathroom_fan:
    name: En-Suite Bathroom Fan
    duration: "01:00:00"
    icon: mdi:fan
  
###########################
#       Toggle            #
###########################

input_boolean:
  main_bedroom_bedside_lamps_active:
    name: Main Bedroom Bedside Lamps Active
    icon: mdi:lamp
  wakeup_lights:
    name: Bedroom Wakeup Lights
    icon: mdi:white-balance-sunny 
  
###########################
#       Number            #
###########################

input_number:
  main_bedroom_sleep:
    name: Main Bedroom Sleep
    initial: 255
    min: 0
    max: 255
    step: 4.25
    mode: box
    icon: mdi:numeric
    unit_of_measurement: "lux"
  main_bedroom_wake:
    name: Main Bedroom Wake
    initial: 0
    min: 0
    max: 255
    step: 8.5
    mode: box
    icon: mdi:numeric
    unit_of_measurement: "lux"
  en_suite_fan_activate:
    name: En-Suite Fan Activate
    initial: 1
    min: 1
    max: 30
    step: 1
    mode: slider
    icon: mdi:fan
    unit_of_measurement: "%"
  en_suite_fan_deactivate:
    name: En-Suite Fan Deactivate
    initial: 65
    min: 35
    max: 100
    step: 1
    mode: slider
    icon: mdi:fan
    unit_of_measurement: "%"
  en_suite_humidity_high:
    name: En-Suite Humidity High
    initial: 85
    min: 65
    max: 100
    step: 1
    mode: slider
    icon: mdi:water-percent
    unit_of_measurement: "%"

###########################
#       Automation        #
###########################
automation:
###########################
#       Lights            #
###########################

  - id: main_bedroom_lights_with_presence
    alias: Main Bedroom Lights with Presence
    description: ""
    initial_state: true
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.main_bedroom_fp2_presence_sensor_2
          - binary_sensor.main_bedroom_fp2_presence_sensor_3
        id: Lights On
        from: "off"
        to: "on"
      - platform: state
        entity_id:
          - binary_sensor.main_bedroom_fp2_presence_sensor_2
          - binary_sensor.main_bedroom_fp2_presence_sensor_3
        id: Lights Off
        from: "on"
        to: "off"
        for:
          hours: 0
          minutes: 1
          seconds: 0
      - platform: numeric_state
        entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
        below: input_number.low_light_threshold
        id: Low Light
      - platform: numeric_state
        entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
        id: Good Light
        above: input_number.upper_light_threshold_level
    condition:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "off"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Lights On
              - condition: template
                value_template: "{{\"Daves\" in trigger.to_state.attributes.friendly_name }}"
                alias: Filter Dave's side of bed
              - condition: numeric_state
                entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
                below: input_number.low_light_threshold
              - condition: state
                entity_id: input_boolean.main_bedroom_bedside_lamps_active
                state: "on"
              - condition: state
                entity_id: binary_sensor.lights_out
                state: "off"
            sequence:
              - service: light.turn_on
                data:
                  brightness_pct: 5
                  color_temp: 500
                target:
                  entity_id: light.sonoff_1001f6d950
          - conditions:
              - condition: trigger
                id:
                  - Lights On
              - condition: template
                value_template: "{{\"Gem\" in trigger.to_state.attributes.friendly_name }}"
                alias: Filter Gem's side of bed
              - condition: numeric_state
                entity_id: sensor.main_bedroom_fp2_light_sensor_light_level
                below: input_number.low_light_threshold
              - condition: state
                entity_id: input_boolean.main_bedroom_bedside_lamps_active
                state: "on"
              - condition: state
                entity_id: binary_sensor.lights_out
                state: "off"
            sequence:
              - service: light.turn_on
                data:
                  color_temp: 500
                  brightness_pct: 5
                target:
                  entity_id: light.sonoff_1001f6d982
          - conditions:
              - condition: trigger
                id:
                  - Lights Off
              - condition: template
                value_template: "{{\"Daves\" in trigger.to_state.attributes.friendly_name }}"
                alias: Filter Dave's side of bed
              - condition: state
                state: "on"
                entity_id: light.sonoff_1001f6d950
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.sonoff_1001f6d950
          - conditions:
              - condition: trigger
                id:
                  - Lights Off
              - condition: template
                value_template: "{{\"Gem\" in trigger.to_state.attributes.friendly_name }}"
                alias: Filter Gem's side of bed
              - condition: state
                state: "on"
                entity_id: light.sonoff_1001f6d982
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id: light.sonoff_1001f6d982
          - conditions:
              - condition: trigger
                id:
                  - Low Light
              - condition: state
                entity_id: input_boolean.room_occupied_main_bedroom
                state: "on"
              - condition: state
                entity_id: input_boolean.main_bedroom_bedside_lamps_active
                state: "on"
              - condition: state
                entity_id: binary_sensor.lights_out
                state: "off"
            sequence:
              - service: light.turn_on
                data:
                  color_temp: 500
                  brightness_pct: 5
                target:
                  entity_id:
                    - light.sonoff_1001f6d950
                    - light.sonoff_1001f6d982
          - conditions:
              - condition: trigger
                id:
                  - Good Light
              - condition: or
                conditions:
                  - condition: state
                    entity_id: light.sonoff_1001f6d950
                    state: "on"
                  - condition: state
                    entity_id: light.sonoff_1001f6d982
                    state: "on"
            sequence:
              - service: light.turn_off
                data: {}
                target:
                  entity_id:
                    - light.sonoff_1001f6d982
                    - light.sonoff_1001f6d950

###########################
#       Wake Up Lights    #
###########################

  - id: main_bedroom_wakeup_lights
    alias: Main Bedroom Wakeup Lights
    description: "Turn on wakeup lights once sunrise is later than 7am"
    initial_state: true
    mode: single
    trigger: 
      - platform: template
        value_template: "{% if (as_timestamp(states('sensor.sun_next_rising')) | timestamp_custom ('%H')) | float(0) > 7 %} true {% endif %}"
        id: Activate
      - platform: template
        value_template: "{% if (as_timestamp(states('sensor.sun_next_rising')) | timestamp_custom ('%H')) | float(0) < 7 %} true {% endif %}"
        id: Deactivate
      - platform: state
        entity_id: binary_sensor.morning
        state: "on"
        id: Wake Up
    condition:
      condition: state
      entity_id: input_boolean.wakeup_lights
      state: "on"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Activate
            sequence:
              - service: input_boolean.turn_on
                data: {}
                target:
                  entity_id: input_boolean.wakeup_lights
          - conditions:
              - condition: trigger
                id:
                  - Deactivate
            sequence:
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: input_boolean.wakeup_lights
          - conditions:
              - condition: trigger
                id:
                  - Wake Up
              - condition: state
                entity_id: input_boolean.wakeup_lights
                state: "on"
            sequence:      
              - service: script.main_bedroom_morning_wakeup_lighting

###########################
#       En-Suite Fan      #
###########################

  - id: 1683829474990
    alias: En-Suite Bathroom Fan On/Off with Humidity Level or Off with Timer
    description: ""
    initial_state: true
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.en_suite_temperature_and_humidity_humidity
        below: 65
        id: Humidity Normal
        alias: When En-Suite humidity is below 65%
      - platform: state
        entity_id:
          - binary_sensor.quiet_time
        from: "off"
        to: "on"
        id: Quiet Time Start
      - platform: state
        entity_id:
          - binary_sensor.quiet_time
        to: "off"
        id: Quiet Time End
        from: "on"
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.en_suite_bathroom_fan
        id: En-Suite Fan Off
        alias: En-Suite Fan off with timer
      - platform: numeric_state
        entity_id: sensor.en_suite_humidity_change
        above: input_number.en_suite_fan_activate
        id: Shower On
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Shower On
              - condition: state
                entity_id: switch.en_suite_fan_switch
                state: "off"
              - condition: state
                entity_id: binary_sensor.quiet_time
                state: "off"
            sequence:
              - type: turn_on
                device_id: b5edcb03424d315e8e0842e735d916f7
                entity_id: switch.en_suite_fan_switch
                domain: switch
              - service: timer.start
                data: {}
                target:
                  entity_id: timer.en_suite_bathroom_fan
          - conditions:
              - condition: trigger
                id:
                  - Humidity Normal
                  - En-Suite Fan Off
              - condition: state
                entity_id: switch.en_suite_fan_switch
                state: "on"
            sequence:
              - type: turn_off
                device_id: b5edcb03424d315e8e0842e735d916f7
                entity_id: switch.en_suite_fan_switch
                domain: switch
          - conditions:
              - condition: trigger
                id: Quiet Time Start
            sequence:
              - if:
                  - condition: state
                    entity_id: switch.en_suite_fan_switch
                    state: "on"
                then:
                  - type: turn_off
                    device_id: b5edcb03424d315e8e0842e735d916f7
                    entity_id: switch.en_suite_fan_switch
                    domain: switch
          - conditions:
              - condition: trigger
                id: Quiet Time End
            sequence:
              - if:
                  - condition: state
                    entity_id: switch.en_suite_fan_switch
                    state: "off"
                  - condition: numeric_state
                    entity_id: sensor.en_suite_temperature_and_humidity_humidity
                    above: input_number.en_suite_humidity_high
                    alias: Confirm En-Suite humidity is above 75%
                then:
                  - type: turn_on
                    device_id: b5edcb03424d315e8e0842e735d916f7
                    entity_id: switch.en_suite_fan_switch
                    domain: switch
                  - service: timer.start
                    data: {}
                    target:
                      entity_id: timer.en_suite_bathroom_fan


###########################
#       Script            #
###########################
script:

###########################
# Bed Lights with Level   #
###########################

  main_bedroom_bed_lights_night_dim:
    alias: Main Bedroom bed lights with level
    sequence:
    - service: light.turn_on
      entity_id: light.bed_lamps
      data:
        brightness: "{{ level | int }} \n"
    mode: single

###########################
# Bed Lights Dim at Night #
###########################  

bed_lamps_dim_at_bedtime:
  alias: Bed lamps dim at Bedtime
  sequence:
  - service: input_number.set_value
    data:
      value: 255
    target:
      entity_id: input_number.main_bedroom_sleep
  - repeat:
      while:
      - condition: template
        value_template: '{{ states("input_number.main_bedroom_sleep") | int > 0 }}'
      sequence:
      - service: script.turn_on
        data:
          level: '{{ states("input_number.main_bedroom_sleep") }}'
        target:
          entity_id: script.main_bedroom_bed_lights_night_dim
      - service: input_number.decrement
        target:
          entity_id: input_number.main_bedroom_sleep
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 30
          milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.bed_lamps
  - service: input_number.set_value
    data:
      value: 255
    target:
      entity_id: input_number.main_bedroom_sleep
  mode: single

##############################
# Bed Lights Wakeup Lighting #
##############################

  main_bedroom_morning_wakeup_lighting:
    sequence:
      - service: input_number.set_value
        data:
          value: 8.5
        target:
          entity_id: input_number.main_bedroom_wake          
      - repeat:
          while:
            - condition: template
              value_template: "{{ states('input_number.main_bedroom_wake') | int < 256 }}"
          sequence:
            - service:  script.turn_on
              data:
                  level: '{{ states("input_number.main_bedroom_wake") }}'
              target:
                entity_id: script.main_bedroom_bed_lights_night_dim
            - service: input_number.increment
              entity_id: input_number.main_bedroom_wake
            - delay: 00:01:00
      - service: input_number.set_value
        data:
          value: 8.5
        target:
          entity_id: input_number.main_bedroom_wake
