###############################################################################
#   @author               :   Jeffrey Stone
#   @date                 :   02/19/2019
#   @package              :   Presence
#   @description          :   A Collection of Presence Related Trackers and Sensors
#
#   @modified by          :   Chris Heder (@chrisron95)
#   @date                 :   05/12/2022
#  
#   @further modified by  :   Dave Forrester (@Daverover66)
#   @date                 :   20/01/2024
###############################################################################    

##############################
#        Helpers             #
##############################
    
##############################
#        Datetime            #
##############################

input_datetime:
  last_time_home_dave:
    name: Dave Last Seen
    has_date: true
    has_time: true
  last_time_home_gem:
    name: Gem Last Seen
    has_date: true
    has_time: true
#  last_time_home_kaitlyn:
#    name: Kaitlyn Last Seen
#    has_date: true
#    has_time: true

##############################
#        Text                #
##############################

##############################
#        Group               #
##############################

group:
  family:
    name: Family
    entities:
      - person.david_forrester
      - person.gem_forrester
      - sensor.dave_is_in_da_hoose
      - sensor.gem_is_in_da_hoose

  arriving:
    name: Arriving
    entities: []

  house_presence:
    name: House Presence
    entities: []

  upstairs_presence:
    name: Upstairs Presence
    entities:
      - binary_sensor.main_bedroom_fp2_presence_sensor_1
      - binary_sensor.guest_bedroom_camera_cell_motion_detection
      - binary_sensor.jamie_s_room_camera_cell_motion_detection
      - binary_sensor.sean_s_room_camera_cell_motion_detection
      - binary_sensor.loft_camera_cell_motion_detection
      - binary_sensor.guest_bedroom_motion_occupancy
      - binary_sensor.jack_and_jill_presence_occupancy
      - binary_sensor.jamie_room_presence_occupancy
      - binary_sensor.sean_room_presence_occupancy
      - binary_sensor.main_bathroom_presence_occupancy
      - binary_sensor.office_presence_sensor_occupancy
      - binary_sensor.upper_landing_presence_occupancy
      

  downstairs_presence:
    name: Downstairs Presence
    entities:
      - binary_sensor.hallway_camera_cell_motion_detection
      - binary_sensor.camera_hub_g3_ddd9_motion_sensor
      - binary_sensor.kitchen_presence_sensor_presence_sensor_1
      - binary_sensor.living_room_fp2_presence_sensor_1
      - binary_sensor.hallway_presence_occupancy
      - binary_sensor.hallway_presence_2_occupancy
      - binary_sensor.cloakroom_presence_occupancy
      - binary_sensor.dining_room_presence_sensor_occupancy
      - binary_sensor.lower_landing_motion_occupancy
      - binary_sensor.utility_room_presence_2_occupancy


##############################
#        Sensors             #
##############################

template:        
##############################
#        MQTT                #
##############################

mqtt:
  sensor:
    - name: "Family Arrived"
      state_topic: "house/family/arrived"
      payload_available: "online"
      payload_not_available: "offline"
    - name: "Family Arrived"
      state_topic: "house/family/arrived"
      payload_available: "online"
      payload_not_available: "offline"

##############################
#        Template            #
##############################

template:      
  - sensor:
      - name: "Dave"
        unique_id: dave_location
        state: >-
          {% set person = states('person.david_forrester') %}
          {%- if person in ['abbotsford','abbotsford_house'] %}
            Abbotsford House
          {% elif person in ['Asda'] %}
            Asda
          {% elif person in ['dave_s_mum_and_dad'] %}
            Daves Mum and Dad
          {% elif person in ['dawn','john','dawn_john'] %}
            The Winpennys
          {% elif person in ['dentist'] %}
            Penicuik Dentist
          {% elif person in ['doctors','surgery','doctors_surgery'] %}
            St Ronans Health Centre
          {% elif person in ['galashiels','playpark','galashiels_playpark'] %} 
            Galashiels Playpark
          {% elif person in ['gem_s_mum_and_dad'] %}
            Moxo and Poxo
          {% elif person in ['gem_work'] %}
            Gems Work
          {% elif person in ['harestanes'] %}
            Harestanes Adventure Park
          {% elif person in ['tesco'] %} 
            Tesco
          {% elif person in ['karen'] %}
            Karens Place
          {% elif person in ['swimming'] %}
            Galashiels Swimming Pool
          {% else %}
            {% if person in ['not_home','away'] %}
              {{ states('sensor.daves_samsung_galaxy_geocoded_location') }} 
            {% else %}
              {{ states('person.david_forrester') }}
            {%- endif %}
          {%- endif %}
 
      - name: "Gem"
        unique_id: gem_location
        state: >-
          {% set person = states('person.gem_forrester') %}
          {%- if person in ['abbotsford','abbotsford_house'] %}
            Abbotsford House
          {% elif person in ['Asda'] %}
            Asda
          {% elif person in ['dave_s_mum_and_dad'] %}
            Daves Mum and Dad
          {% elif person in ['dawn','john','dawn_john'] %}
            The Winpennys
          {% elif person in ['dentist'] %}
            Penicuik Dentist
          {% elif person in ['doctors','surgery','doctors_surgery'] %}
            St Ronans Health Centre
          {% elif person in ['galashiels','playpark','galashiels_playpark'] %} 
            Galashiels Playpark
          {% elif person in ['gem_s_mum_and_dad'] %}
            Moxo and Poxo
          {% elif person in ['gem_work'] %}
            Gems Work
          {% elif person in ['harestanes'] %}
            Harestanes Adventure Park
          {% elif person in ['tesco'] %} 
            Tesco
          {% elif person in ['karen'] %}
            Karens Place
          {% elif person in ['swimming'] %}
            Galashiels Swimming Pool
          {% else %}
            {% if person in ['not_home','away'] %}
              {{ states('sensor.sm_s901b_geocoded_location') }} 
            {% else %}
              {{ states('person.gem_forrester') }}
            {%- endif %}
          {%- endif %}

automation:

##############################
#        Automations         #
##############################

##############################
#        Family Arrived      #
##############################

    - id: family_has_arrived
      alias: Family Has Arrived
      description: ""
      mode: single
      initial_state: true
      trigger:
        - platform: state
          entity_id:
            - binary_sensor.family_home
          from: "off"
          to: "on"
          id: Auto
        - platform: state
          entity_id:
            - input_boolean.family_is_home
          from: "off"
          to: "on"
          id: Manual
      condition:
        - condition: state
          entity_id: input_boolean.family_is_home
          state: "off"
      action:
        - service: input_boolean.turn_on
          data: {}
          target:
            entity_id: input_boolean.family_is_home
      
##############################
#        Family Left         #
##############################

  - id: family_has_left
    alias: "Family has left"
    description: ""
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.family_home
        from: "on"
        to: "off"
        id: Auto
      - platform: state
        entity_id:
          - input_boolean.family_is_home
        from: "on"
        to: "off"
        id: Manual
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - Auto
            sequence:
              - service: input_boolean.turn_off
                data: {}
                target:
                 entity_id: input_boolean.family_is_home

###########################
#         Travel          #
###########################


    
####################################
#          Welcome Home            #
####################################

  - id: welcome_home
    alias: Welcome Home
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - person.david_forrester
          - person.gem_forrester
        from: "not_home"
        to: "home"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.welcome_home
                state: "on"
            sequence:
              - wait_for_trigger:
                  - platform: state
                    entity_id: binary_sensor.front_door_sense_contact
                    from: "off"
                    to: "on"
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 10
                  milliseconds: 0
              - service: script.turn_on
                entity_id: script.welcome_briefing
        default:
          - service: group.set
            data:
              object_id: "arriving"
              add_entities: >-
                {{ trigger.to_state.entity_id }}
          - wait_for_trigger:
              - platform: state
                entity_id: binary_sensor.front_door
                from: "off"
                to: "on"
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - service: script.status_annc
            data:
              who: "{{ states('sensor.room_presence') }}"
              call_interuption: 1
              speech_message: >
                {% set person = expand('group.arriving')|map(attribute='name')|join(' and ') %}
                {% set peoplecount = expand('group.arriving') | count %}
                {% if peoplecount == 1 %}
                  {% set is_are = ' is ' %}
                  {% set has_have = ' has ' %}
                {% else %}
                  {% set is_are = ' are ' %}
                  {% set has_have = ' have ' %}
                {% endif %}
                {%- macro greeting_sentence(person, is_are, has_have) -%}
                  {{ [
                  person ~ has_have + " arrived.",
                  "My sensors are picking up the presence of additional humans. " ~ person ~ has_have + " been identified as home.",
                  "Guess who is in the hub?" ~ person ~ is_are,
                  "I am sensing a disturbance in the force. "  ~ person +" must be back!",
                  person ~ is_are + "now in the house.",
                  person  ~ is_are + " now here.  Welcome Home.",
                  person  ~ is_are + " now here.",
                  "Just a quick announcement. " ~ person ~ has_have + "  arrived!",
                  person ~ has_have + " finally made it home."
                  ] | random }}
                {%- endmacro -%}
                {{greeting_sentence(person, is_are, has_have)}}
          - delay: 00:02:00
          - service: group.set
            data:
              object_id: "arriving"
              entities: []

  - id: guests_have_arrived
    alias: Guests have arrived
    trigger:
      - platform: state
        entity_id:
          - person.kaitlyn
          - person.ronald
          - person.mari
          - person.rheena
          - person.danielle
          - person.daniel
          - person.brian
          - person.rathnam
          - person.nico
        from: "not_home"
        to: "home"
    action:
      # - service: script.standby
      - service: script.family_is_home
      - service: script.visitors_here
    initial_state: true

  - id: guests_have_left
    alias: Guests have left
    trigger:
      - entity_id: group.friends
        from: home
        to: not_home
        platform: state
    action:
      - service: script.visitors_gone
      - condition: not
        conditions:
          - condition: state
            entity_id: group.family
            state: home
      - service: script.family_is_away
        data: {}
    initial_state: true

script:
  family_is_home:
    sequence:
      - condition: state
        entity_id: group.family
        state: "home"
      - service: script.standby

  family_is_away:
    sequence:
      - condition: state
        entity_id: group.family
        state: "not_home"
      # - service: script.appliances_off
      - service: scene.turn_on
        entity_id: scene.all_off
      - service: input_boolean.turn_on
        entity_id: input_boolean.sentry_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.motion_lights_master
      # - service: scene.turn_on
      #   entity_id: scene.all_fans_off
      - service: input_boolean.turn_on
        entity_id: input_boolean.welcome_home
