###############################################################################
#   @author         :   Jeffrey Stone
#   @date           :   03/13/2019
#   @package        :   Security
#   @description    :   Everything related to security functions.
#
#   @modified by    :   David Forrester
#   @date           :   31/03/2024
###############################################################################

##################
#     Groups     # 
##################

group:
  ground_floor_windows:
    name: Ground Floor Windows
    icon: mdi:window-closed-variant 
    entities:
      - binary_sensor.cloakroom_window_contact
      - binary_sensor.hallway_window_contact
      - binary_sensor.kitchen_window_left_contact
      - binary_sensor.kitchen_window_right_contact
      - binary_sensor.living_room_window_left_contact
      - binary_sensor.living_room_window_right_contact
      - binary_sensor.dining_room_window_left_contact
      - binary_sensor.dining_room_window_right_contact

  first_floor_windows:
    name: First Floor Windows
    icon: mdi:window-closed-variant 
    entities: 
      - binary_sensor.en_suite_window_sensor_contact
      - binary_sensor.office_window_sensor_contact
      - binary_sensor.main_bedroom_window_left_contact
      - binary_sensor.main_bedroom_window_right_contact
      - binary_sensor.bathroom_window_contact
      - binary_sensor.guest_bedroom_window_left_contact
      - binary_sensor.guest_bedroom_window_right_contact
      - binary_sensor.sean_s_bedroom_window_left_contact
      - binary_sensor.sean_s_bedroom_window_right_contact
      - binary_sensor.jamie_s_bedroom_window_left_contact
      - binary_sensor.jamie_s_bedroom_window_right_contact
      - binary_sensor.kids_bathroom_window_left_contact
      - binary_sensor.kids_bathroom_window_right_contact

  external_doors:
    name: External Doors
    icon: mdi:door-closed
    entities:
      - binary_sensor.back_door_sensor_contact
      - binary_sensor.front_door_sense_contact
      - binary_sensor.side_door_sensor_contact
      - binary_sensor.garage_door_left_contact
      - binary_sensor.garage_door_right_contact

##################
#     Sensors    # 
##################

##################
#   Statistics   # 
##################

sensor:
  - platform: history_stats
    name: Front Door Motion Yesterday
    entity_id: binary_sensor.front_doorbell_camera_motion
    state: 'on'
    type: count 
    end: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    duration:
      hours: 24
  - platform: history_stats
    name: Doorbell Presses Yesterday
    entity_id: binary_sensor.front_doorbell_camera_visitor
    state: 'on'
    type: count 
    end: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
    duration:
      hours: 24
