###############################################################################
#   @author         :   Dave Forrester (@Daverover66)
#   @date           :   08/09/2023
#   @package        :   Tablets
#   @description    :   All Tablets config
#
#   @modified by    :   Dave Forrester
#   @date           :   10/10/2023
###############################################################################

automation:
  - id: all_tablet_automations
    alias: All Tablet Automations
    initial_state: true
    mode: single
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.sm_t736b_battery_level
        above: 99
        id: Daves tablet charged
      - platform: numeric_state
        entity_id: sensor.kfmuwi_battery_level
        below: 20
        id: Gems Kindle Battery low
      - platform: state
        entity_id: sensor.jamie_s_samsung_tablet_network_type
        id: Jamie Network Type
      - platform: numeric_state
        entity_id: sensor.jamie_s_samsung_tablet_battery_level
        below: 10
        id: Jamie Low Battery
      - platform: numeric_state
        entity_id: sensor.jamie_s_samsung_tablet_battery_level
        above: 99
        id: Jamie Fully Charged
      - platform: state
        entity_id: sensor.sean_s_samsung_galaxy_network_type
        id: Sean Network Type
      - platform: numeric_state
        entity_id: sensor.sean_s_samsung_galaxy_battery_level
        below: 10
        id: Sean Low Battery
      - platform: numeric_state
        entity_id: sensor.sean_s_samsung_galaxy_battery_level
        above: 99
        id: Sean Fully Charged
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: Daves tablet charged
            sequence:
              - service: script.text_notify_dave
                data:
                  title: TABLET CHARGED
                  message: Your tablet is charged.
          - conditions:
              - condition: trigger
                id: Gems Kindle Battery low
            sequence:
              - service: script.text_notify_gem
                data:
                  title: GEM KINDLE
                  message: Gems Kindle battery is low, please charge.                  
             - service: script.text_notify_dave
               data:
                 title: GEM KINDLE
                 message: Gems Kindle battery is low, please charge.
          - conditions: 
               - condition: trigger
                 id: Jamie Network Type
               - condition: state
                 entity_id: person.jamie
                 state: home
            sequence:
              - service: script.text_notify_dave
                data:
                  title: JAMIE TABLET
                  message: Jamie's tablet has changed network.
          - conditions:
              - condition: trigger
                id: Jamie Low Battery
            sequence:
              - service: script.text_notify_dave
                data:
                  title: JAMIE TABLET
                  message: Jamie's tablet needs charged.
          - conditions:
              - condition: trigger
                id: Jamie Fully Charged
            sequence:
              - service: script.text_notify_dave
                data:
                  title: JAMIE TABLET
                  message: Jamie's tablet is charged.
          - conditions:
              - condition: trigger
                id: Sean Network Type
              - condition: state
                entity_id: person.sean
                state: home
            sequence:
              - service: script.text_notify_dave
                data:
                  title: SEAN TABLET
                  message: Sean's tablet has changed network.
          - conditions:
              - condition: trigger
                id: Sean Low Battery
            sequence:
              - service: script.text_notify_dave
                data:
                  title: SEAN TABLET
                  message: Sean's tablet needs charged.
          - conditions:
              - condition: trigger
                id: Sean Fully Charged
            sequence:
              - service: script.text_notify_dave
                data:
                  title: SEAN TABLET
                  message: Sean's tablet is charged.
                  
    



