###############################################################################
#   @author         :   Dave Forrester (@Daverover66)
#   @date           :   08/09/2023
#   @package        :   Tablets
#   @description    :   All Tablets config
#
#   @modified by    :   Dave Forrester
#   @date           :   10/10/2023
###############################################################################

automation:
  - id: all_tablet_automations
    alias: All Tablet Automations
    initial_state: true
    mode: single
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.sm_t736b_battery_level
        above: 99
        id: Daves tablet charged
    condition: []
    action:
      choose:
        conditions:
          - condition: trigger
            id: Daves tablet charged
        sequence:
          - service: notify.mobile_app_daves_samsung_galaxy
            data:
              message: Your tablet is charged.
    mode: single

alias: Gem's Kindle Battery Watch
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.kfmuwi_battery_level
    below: 20
condition: []
action:
  - service: notify.mobile_app_{{states('input_text.gem_s_mobile_phone_id')}}
    data:
      message: Kindle battery is low, please charge.
    alias: Send a notification based on an input text helper
  - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
    data:
      message: Kindle battery is low, please charge.
      title: GEM'S KINDLE
    alias: Send a notification based on an input text helper
mode: single

alias: "Jamie's Tablet All Automations "
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.jamie_s_samsung_tablet_network_type
    id: Network Type
  - platform: numeric_state
    entity_id: sensor.jamie_s_samsung_tablet_battery_level
    below: 10
    id: Low Battery
  - platform: numeric_state
    entity_id: sensor.jamie_s_samsung_tablet_battery_level
    above: 99
    id: Fully Charged
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Network Type
          - condition: state
            entity_id: person.jamie
            state: home
        sequence:
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: Jamie's tablet has changed network
              title: NETWORK CHANGE
            alias: Send a notification based on an input text helper
      - conditions:
          - condition: trigger
            id:
              - Low Battery
        sequence:
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: Jamie's tablet needs charged
              title: TABLET LOW BATTERY
            alias: Send a notification based on an input text helper
      - conditions:
          - condition: trigger
            id:
              - Fully Charged
        sequence:
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: Jamie's tablet is charged
              title: TABLET CHARGED
            alias: Send a notification based on an input text helper
mode: single

alias: Sean's Tablet All Automation
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.sean_s_samsung_galaxy_network_type
    id: Network Type
  - platform: numeric_state
    entity_id: sensor.sean_s_samsung_galaxy_battery_level
    below: 10
    id: Low Battery
  - platform: numeric_state
    entity_id: sensor.sean_s_samsung_galaxy_battery_level
    above: 99
    id: Fully Charged
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Network Type
          - condition: state
            entity_id: person.sean
            state: home
        sequence:
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: Sean's tablet has changed network
              title: NETWORK CHANGE
            alias: Send a notification based on an input text helper
      - conditions:
          - condition: trigger
            id:
              - Low Battery
        sequence:
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: Sean's tablet needs charged
              title: TABLET LOW BATTERY
            alias: Send a notification based on an input text helper
      - conditions:
          - condition: trigger
            id:
              - Fully Charged
        sequence:
          - service: notify.mobile_app_{{states('input_text.my_mobile_phone_id')}}
            data:
              message: Sean's tablet is charged
              title: TABLET CHARGED
            alias: Send a notification based on an input text helper
mode: single
